import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: ['intro', 'overview/core-concepts']
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/intro',
        'getting-started/first-workspace',
        'getting-started/first-entity',
        'getting-started/first-project-diagram',
        'getting-started/next-steps',
        {
          type: 'doc',
          id: 'getting-started/installation',
          label: 'Local Development Setup'
        }
      ]
    },
    {
      type: 'category',
      label: 'Product Guides',
      items: [
        {
          type: 'category',
          label: 'Catalog and Discovery',
          items: [
            'use/workspace-home-navigation',
            'use/workspace-dashboards',
            'use/search',
            'use/data-modeling-schemas',
            'use/entities',
            'use/entity-views'
          ]
        },
        {
          type: 'category',
          label: 'Projects and Content',
          items: ['use/projects', 'use/assessments', 'use/content']
        },
        {
          type: 'category',
          label: 'Collaboration and Governance',
          items: ['use/collaboration-notifications', 'use/governance']
        },
        {
          type: 'category',
          label: 'AI and Account Settings',
          items: ['use/ai-assistant-extract', 'use/account-settings']
        }
      ]
    },
    {
      type: 'category',
      label: 'Workspace Administration',
      items: [
        'admin/overview',
        'admin/identity-and-authentication',
        'admin/workspace-settings',
        'admin/workspace-templates-capabilities',
        'admin/analytics-and-audit',
        'admin/public-catalog',
        'admin/schemas-model-overview',
        'admin/document-types-templates',
        'admin/teams-members',
        'admin/roles-permissions',
        'admin/ai-configuration',
        'admin/export-import'
      ]
    },
    {
      type: 'category',
      label: 'Application Guides',
      link: {
        type: 'doc',
        id: 'applications/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'applications/guides'
        }
      ]
    },
    {
      type: 'category',
      label: 'Reference and Integrations',
      items: [
        {
          type: 'category',
          label: 'Product Reference',
          items: [
            'reference/scope-matrix',
            'reference/permission-model',
            'reference/entity-screen-reference',
            'reference/project-content-screen-reference'
          ]
        },
        {
          type: 'category',
          label: 'APIs and Integrations',
          items: [
            'reference/api-integrations',
            'reference/mcp-server',
            'reference/external-integrations',
            {
              type: 'link',
              label: 'API Reference',
              href: 'pathname:///arch-register/api.html'
            }
          ]
        }
      ]
    }
  ],
};

export default sidebars;
