import type { SeedEntityInput } from '../../db/seedData/entities';
import {
  DEMO_GLOSSARY_IDS,
  GLOSSARY_IDS,
  LIFECYCLE_IDS,
  TEAM_IDS,
  WORKSPACE_ID,
  now
} from '../../db/seedData/constants';

// The demo bootstrap dataset's business glossary: 8 categories, 35 terms, themed around an online
// retailer. Terms link to categories via the plain `categories` reference field (no relation-schema
// rows involved). Replaces the 3 Term Categories / 4 Terms in entities.ts:2376-2541 for the demo
// dataset.
export const demoTermCategoryEntities: SeedEntityInput[] = [
  {
    id: DEMO_GLOSSARY_IDS.categories.catalogMerchandising,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-1',
    slug: 'catalog-and-merchandising',
    namespace: 'default',
    name: 'Catalog & Merchandising',
    description: 'Terms describing product catalog structure and merchandising.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'merchandising'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.customerIdentity,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-2',
    slug: 'customer-and-identity',
    namespace: 'default',
    name: 'Customer & Identity',
    description: 'Terms describing customers, accounts, and identity concepts.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'customer'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.ordersFulfillment,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-3',
    slug: 'orders-and-fulfillment',
    namespace: 'default',
    name: 'Orders & Fulfillment',
    description: 'Terms describing order processing, warehousing, and delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'fulfillment'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.paymentsFinance,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-4',
    slug: 'payments-and-finance',
    namespace: 'default',
    name: 'Payments & Finance',
    description: 'Terms describing payment processing and financial operations.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'payments'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.marketingGrowth,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-5',
    slug: 'marketing-and-growth',
    namespace: 'default',
    name: 'Marketing & Growth',
    description: 'Terms describing customer acquisition and marketing performance.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'marketing'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.dataAnalytics,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-6',
    slug: 'data-and-analytics',
    namespace: 'default',
    name: 'Data & Analytics',
    description: 'Terms describing data, metrics, and analytical products.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'data'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.technologyArchitecture,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-7',
    slug: 'technology-and-architecture',
    namespace: 'default',
    name: 'Technology & Architecture',
    description: 'Terms describing systems, platforms, and architecture concepts.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'architecture'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_GLOSSARY_IDS.categories.riskCompliance,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-8',
    slug: 'risk-and-compliance',
    namespace: 'default',
    name: 'Risk & Compliance',
    description: 'Terms describing risk, privacy, and regulatory compliance concepts.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'compliance'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

const term = (
  publicId: string,
  key: keyof typeof DEMO_GLOSSARY_IDS.terms,
  slug: string,
  name: string,
  definition: string,
  synonyms: string[],
  abbreviations: string[],
  categories: string[],
  status: 'draft' | 'proposed' | 'approved',
  owner: string,
  tags: string[]
): SeedEntityInput => ({
  id: DEMO_GLOSSARY_IDS.terms[key],
  workspace: WORKSPACE_ID,
  public_id: publicId,
  slug,
  namespace: 'default',
  name,
  description: definition,
  owner,
  lifecycle: LIFECYCLE_IDS.production,
  target_lifecycle: null,
  target_lifecycle_date: null,
  tags: ['glossary', ...tags],
  links: [],
  schema_id: GLOSSARY_IDS.termSchema,
  data: { definition, synonyms, abbreviations, categories, status },
  project_id: null,
  created_at: now,
  updated_at: now
});

const C = DEMO_GLOSSARY_IDS.categories;

export const demoTermEntities: SeedEntityInput[] = [
  term(
    'TERM-1',
    'sku',
    'sku',
    'SKU',
    'A unique identifier assigned to a distinct sellable product variant.',
    ['Stock Keeping Unit'],
    ['SKU'],
    [C.catalogMerchandising],
    'approved',
    TEAM_IDS.design,
    ['catalog']
  ),
  term(
    'TERM-2',
    'productVariant',
    'product-variant',
    'Product Variant',
    'A specific version of a product distinguished by attributes such as size or color.',
    ['Variant'],
    [],
    [C.catalogMerchandising],
    'approved',
    TEAM_IDS.design,
    ['catalog']
  ),
  term(
    'TERM-3',
    'assortment',
    'assortment',
    'Assortment',
    'The set of products offered for sale within a category or channel.',
    ['Product Range'],
    [],
    [C.catalogMerchandising],
    'proposed',
    TEAM_IDS.design,
    ['catalog']
  ),
  term(
    'TERM-4',
    'merchandisingRule',
    'merchandising-rule',
    'Merchandising Rule',
    'A configured rule controlling how products are ranked or displayed in search and browse.',
    ['Ranking Rule'],
    [],
    [C.catalogMerchandising],
    'draft',
    TEAM_IDS.design,
    ['catalog']
  ),
  term(
    'TERM-5',
    'customerAccount',
    'customer-account',
    'Customer Account',
    'A record representing a customer relationship and its account-level context.',
    ['Client Account', 'Customer Profile'],
    ['CA'],
    [C.customerIdentity],
    'approved',
    TEAM_IDS.data,
    ['customer']
  ),
  term(
    'TERM-6',
    'guestCheckout',
    'guest-checkout',
    'Guest Checkout',
    'A purchase completed without creating a persistent customer account.',
    [],
    [],
    [C.customerIdentity],
    'approved',
    TEAM_IDS.data,
    ['customer', 'checkout']
  ),
  term(
    'TERM-7',
    'customerLifetimeValue',
    'customer-lifetime-value',
    'Customer Lifetime Value',
    'The predicted net revenue attributable to a customer over the full relationship.',
    [],
    ['CLV'],
    [C.customerIdentity],
    'proposed',
    TEAM_IDS.data,
    ['customer']
  ),
  term(
    'TERM-8',
    'churn',
    'churn',
    'Churn',
    'The loss of customers over a given period, typically expressed as a rate.',
    ['Customer Attrition'],
    [],
    [C.customerIdentity],
    'approved',
    TEAM_IDS.data,
    ['customer']
  ),
  term(
    'TERM-9',
    'segment',
    'segment',
    'Segment',
    'A group of customers sharing common attributes, used for targeting or analysis.',
    [],
    [],
    [C.customerIdentity],
    'approved',
    TEAM_IDS.data,
    ['customer']
  ),
  term(
    'TERM-10',
    'orderOrchestration',
    'order-orchestration',
    'Order Orchestration',
    'The coordination of order processing steps across systems from placement to fulfillment.',
    [],
    [],
    [C.ordersFulfillment],
    'approved',
    TEAM_IDS.platform,
    ['fulfillment']
  ),
  term(
    'TERM-11',
    'fulfillmentCenter',
    'fulfillment-center',
    'Fulfillment Center',
    'A facility where orders are picked, packed, and shipped.',
    ['Warehouse', 'Distribution Center'],
    [],
    [C.ordersFulfillment],
    'approved',
    TEAM_IDS.platform,
    ['fulfillment']
  ),
  term(
    'TERM-12',
    'backorder',
    'backorder',
    'Backorder',
    'An order for a product that is temporarily out of stock, to be fulfilled once restocked.',
    [],
    [],
    [C.ordersFulfillment],
    'proposed',
    TEAM_IDS.platform,
    ['fulfillment']
  ),
  term(
    'TERM-13',
    'lastMileDelivery',
    'last-mile-delivery',
    'Last-Mile Delivery',
    "The final leg of delivery from a fulfillment or transit hub to the customer's address.",
    [],
    [],
    [C.ordersFulfillment],
    'approved',
    TEAM_IDS.platform,
    ['fulfillment']
  ),
  term(
    'TERM-14',
    'returnMerchandiseAuthorization',
    'return-merchandise-authorization',
    'Return Merchandise Authorization',
    'An authorization issued to a customer to return a purchased item.',
    [],
    ['RMA'],
    [C.ordersFulfillment],
    'approved',
    TEAM_IDS.platform,
    ['fulfillment']
  ),
  term(
    'TERM-15',
    'cardholderData',
    'cardholder-data',
    'Cardholder Data',
    'Any data element that appears alongside or as part of a full payment card number.',
    [],
    ['CHD'],
    [C.paymentsFinance],
    'approved',
    TEAM_IDS.payments,
    ['payments']
  ),
  term(
    'TERM-16',
    'chargeback',
    'chargeback',
    'Chargeback',
    "A reversal of a card payment initiated by the cardholder's issuing bank.",
    [],
    [],
    [C.paymentsFinance],
    'approved',
    TEAM_IDS.payments,
    ['payments']
  ),
  term(
    'TERM-17',
    'settlement',
    'settlement',
    'Settlement',
    "The process of transferring authorized payment funds to the merchant's account.",
    [],
    [],
    [C.paymentsFinance],
    'approved',
    TEAM_IDS.payments,
    ['payments']
  ),
  term(
    'TERM-18',
    'paymentGateway',
    'payment-gateway',
    'Payment Gateway',
    'The service that authorizes and routes card payment transactions.',
    [],
    [],
    [C.paymentsFinance],
    'approved',
    TEAM_IDS.payments,
    ['payments']
  ),
  term(
    'TERM-19',
    'reconciliation',
    'reconciliation',
    'Reconciliation',
    'The process of matching recorded transactions against actual settlement data.',
    [],
    [],
    [C.paymentsFinance],
    'proposed',
    TEAM_IDS.payments,
    ['payments']
  ),
  term(
    'TERM-20',
    'conversionRate',
    'conversion-rate',
    'Conversion Rate',
    'The percentage of visits that result in a completed purchase.',
    [],
    ['CVR'],
    [C.marketingGrowth],
    'approved',
    TEAM_IDS.design,
    ['marketing']
  ),
  term(
    'TERM-21',
    'customerAcquisitionCost',
    'customer-acquisition-cost',
    'Customer Acquisition Cost',
    'The average cost of acquiring one new paying customer.',
    [],
    ['CAC'],
    [C.marketingGrowth],
    'proposed',
    TEAM_IDS.design,
    ['marketing']
  ),
  term(
    'TERM-22',
    'cartAbandonment',
    'cart-abandonment',
    'Cart Abandonment',
    'When a shopper adds items to a cart but exits before completing checkout.',
    [],
    [],
    [C.marketingGrowth],
    'approved',
    TEAM_IDS.design,
    ['marketing', 'checkout']
  ),
  term(
    'TERM-23',
    'attributionModel',
    'attribution-model',
    'Attribution Model',
    'The rule set used to assign marketing credit across touchpoints in a customer journey.',
    [],
    [],
    [C.marketingGrowth],
    'draft',
    TEAM_IDS.design,
    ['marketing']
  ),
  term(
    'TERM-24',
    'dataProduct',
    'data-product',
    'Data Product',
    'A data asset designed, documented, and operated for reuse by its consumers.',
    ['Analytical Product'],
    ['DP'],
    [C.dataAnalytics],
    'approved',
    TEAM_IDS.data,
    ['data']
  ),
  term(
    'TERM-25',
    'dataDomain',
    'data-domain',
    'Data Domain',
    'A bounded area of data with shared meaning, ownership, and governance rules.',
    ['Information Domain'],
    ['DD'],
    [C.dataAnalytics, C.technologyArchitecture],
    'draft',
    TEAM_IDS.data,
    ['data', 'architecture']
  ),
  term(
    'TERM-26',
    'clickstream',
    'clickstream',
    'Clickstream',
    "The sequential record of a user's page and event interactions on the site.",
    [],
    [],
    [C.dataAnalytics],
    'approved',
    TEAM_IDS.data,
    ['data']
  ),
  term(
    'TERM-27',
    'dataLineage',
    'data-lineage',
    'Data Lineage',
    'The traceable history of how a data element was produced and transformed.',
    [],
    [],
    [C.dataAnalytics, C.technologyArchitecture],
    'proposed',
    TEAM_IDS.data,
    ['data', 'architecture']
  ),
  term(
    'TERM-28',
    'systemOfRecord',
    'system-of-record',
    'System of Record',
    'The authoritative system responsible for creating and maintaining a data record.',
    ['Authoritative Source'],
    ['SoR'],
    [C.technologyArchitecture],
    'proposed',
    TEAM_IDS.platform,
    ['architecture']
  ),
  term(
    'TERM-29',
    'apiGateway',
    'api-gateway',
    'API Gateway',
    'A managed entry point that routes, authenticates, and rate-limits API traffic.',
    [],
    [],
    [C.technologyArchitecture],
    'approved',
    TEAM_IDS.platform,
    ['architecture']
  ),
  term(
    'TERM-30',
    'idempotencyKey',
    'idempotency-key',
    'Idempotency Key',
    'A client-supplied token used to safely retry a request without duplicating its effect.',
    [],
    [],
    [C.technologyArchitecture],
    'proposed',
    TEAM_IDS.platform,
    ['architecture']
  ),
  term(
    'TERM-31',
    'eventDrivenArchitecture',
    'event-driven-architecture',
    'Event-Driven Architecture',
    'A design style where services communicate by producing and consuming events.',
    [],
    ['EDA'],
    [C.technologyArchitecture],
    'draft',
    TEAM_IDS.platform,
    ['architecture']
  ),
  term(
    'TERM-32',
    'personallyIdentifiableInformation',
    'personally-identifiable-information',
    'Personally Identifiable Information',
    'Any data that could be used, alone or with other data, to identify a specific individual.',
    [],
    ['PII'],
    [C.riskCompliance, C.customerIdentity],
    'approved',
    TEAM_IDS.security,
    ['privacy']
  ),
  term(
    'TERM-33',
    'dataSubject',
    'data-subject',
    'Data Subject',
    'An identified or identifiable natural person whose personal data is processed.',
    [],
    [],
    [C.riskCompliance],
    'approved',
    TEAM_IDS.security,
    ['privacy']
  ),
  term(
    'TERM-34',
    'residualRisk',
    'residual-risk',
    'Residual Risk',
    'The risk remaining after controls and mitigations have been applied.',
    [],
    [],
    [C.riskCompliance],
    'approved',
    TEAM_IDS.security,
    ['risk']
  ),
  term(
    'TERM-35',
    'controlEffectiveness',
    'control-effectiveness',
    'Control Effectiveness',
    'The degree to which a control achieves its intended risk-reduction objective.',
    [],
    [],
    [C.riskCompliance],
    'proposed',
    TEAM_IDS.security,
    ['risk']
  )
];
