ALTER TABLE entity_schema ADD COLUMN IF NOT EXISTS groups JSONB NOT NULL DEFAULT '[]';
ALTER TABLE entity_schema_version ADD COLUMN IF NOT EXISTS groups JSONB NOT NULL DEFAULT '[]';
ALTER TABLE assessment ADD COLUMN IF NOT EXISTS groups JSONB NOT NULL DEFAULT '[]';
