import type { SeedEntityInput } from './entities';
import {
  DEMO_TECHNOLOGY_IDS,
  LIFECYCLE_IDS,
  SEED_SCHEMA_IDS,
  TEAM_IDS,
  WORKSPACE_ID,
  now
} from './constants';

// Technology, Technology Release and Resource entities for the demo dataset - the tech stack
// underpinning the e-commerce systems (Customer Portal, Identity Platform, Payments Platform,
// Analytics Platform, Notification Hub, Search Platform). Technology Release belongs to exactly
// one Technology via a `technology` containment field; Component and Resource each reference zero
// or more Technology Releases via a `technology_releases` field. None of this is relation-schema
// based, so there is no accompanying demoTechnologyRelations.ts.
const T = DEMO_TECHNOLOGY_IDS.technologies;
const REL = DEMO_TECHNOLOGY_IDS.releases;

export const demoTechnologyEntities: SeedEntityInput[] = [
  {
    id: T.nodejs,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-1',
    slug: 'nodejs',
    namespace: 'default',
    name: 'Node.js',
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine.",
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://nodejs.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Node.js',
      provider_product: 'nodejs',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.typescript,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-2',
    slug: 'typescript',
    namespace: 'default',
    name: 'TypeScript',
    description:
      'A strongly typed superset of JavaScript used across the API Gateway and Frontend App.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'javascript'],
    links: [{ url: 'https://www.typescriptlang.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'TypeScript',
      provider_product: 'typescript',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.react,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-3',
    slug: 'react',
    namespace: 'default',
    name: 'React',
    description: 'A JavaScript library for building user interfaces.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['framework', 'frontend'],
    links: [{ url: 'https://react.dev', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'React',
      provider_product: 'react',
      category: 'framework',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.go,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-4',
    slug: 'go',
    namespace: 'default',
    name: 'Go',
    description:
      'An open source programming language that makes it easy to build simple, reliable, and efficient software.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://go.dev', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: { product: 'Go', provider_product: 'go', category: 'language', radar_status: 'adopt' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.python,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-5',
    slug: 'python',
    namespace: 'default',
    name: 'Python',
    description:
      'A programming language used across the data platform for pipelines and analytics jobs.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'data'],
    links: [{ url: 'https://www.python.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Python',
      provider_product: 'python',
      category: 'language',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.java,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-6',
    slug: 'java',
    namespace: 'default',
    name: 'Java',
    description:
      'A high-level, class-based, object-oriented programming language used by the legacy ledger service.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'legacy'],
    links: [{ url: 'https://www.java.com', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: { product: 'Java', provider_product: 'java', category: 'language', radar_status: 'hold' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.postgresql,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-7',
    slug: 'postgresql',
    namespace: 'default',
    name: 'PostgreSQL',
    description: "The world's most advanced open source relational database.",
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'managed'],
    links: [{ url: 'https://www.postgresql.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'PostgreSQL',
      provider_product: 'postgresql',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.redis,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-8',
    slug: 'redis',
    namespace: 'default',
    name: 'Redis',
    description:
      'An open source, in-memory data structure store used for caching and session state.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'cache'],
    links: [{ url: 'https://redis.io', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Redis',
      provider_product: 'redis',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.kafka,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-9',
    slug: 'kafka',
    namespace: 'default',
    name: 'Apache Kafka',
    description:
      'An open-source distributed event streaming platform used as the order/notification event backbone.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['messaging', 'managed'],
    links: [{ url: 'https://kafka.apache.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Apache Kafka',
      provider_product: 'apache-kafka',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.elasticsearch,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-10',
    slug: 'elasticsearch',
    namespace: 'default',
    name: 'Elasticsearch',
    description: 'A distributed, RESTful search and analytics engine powering product search.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-01',
    tags: ['database', 'search'],
    links: [
      { url: 'https://www.elastic.co/elasticsearch', title: 'Official site', type: 'website' }
    ],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Elasticsearch',
      provider_product: 'elasticsearch',
      category: 'database',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.rust,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-11',
    slug: 'rust',
    namespace: 'default',
    name: 'Rust',
    description:
      'A language empowering everyone to build reliable and efficient software, under evaluation for the payments authorization path.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://www.rust-lang.org', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Rust',
      provider_product: 'rust',
      category: 'language',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.kubernetes,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-12',
    slug: 'kubernetes',
    namespace: 'default',
    name: 'Kubernetes',
    description: 'Container orchestration platform hosting the payments services.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'infrastructure'],
    links: [{ url: 'https://kubernetes.io', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Kubernetes',
      provider_product: 'kubernetes',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.docker,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-13',
    slug: 'docker',
    namespace: 'default',
    name: 'Docker',
    description: 'Container runtime and image tooling used across all services.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'infrastructure'],
    links: [{ url: 'https://www.docker.com', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Docker',
      provider_product: 'docker',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: T.snowflake,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-14',
    slug: 'snowflake',
    namespace: 'default',
    name: 'Snowflake',
    description:
      'Cloud data warehouse platform under evaluation to replace the self-managed analytics warehouse.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'warehouse'],
    links: [{ url: 'https://www.snowflake.com', title: 'Official site', type: 'website' }],
    schema_id: SEED_SCHEMA_IDS.technology,
    data: {
      product: 'Snowflake',
      provider_product: 'snowflake',
      category: 'database',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoTechnologyReleaseEntities: SeedEntityInput[] = [
  {
    id: REL.nodejs22,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-1',
    slug: 'nodejs-22',
    namespace: 'default',
    name: 'Node.js 22',
    description: 'Node.js 22 release cycle tracked for runtime support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://endoflife.date/nodejs', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.nodejs],
      provider_product: 'nodejs',
      release_cycle: '22',
      latest_version: '22.13.0',
      release_date: '2024-04-24',
      active_support_until: '2025-10-22',
      security_support_until: '2027-04-30',
      eol_date: '2027-04-30',
      source_url: 'https://endoflife.date/nodejs',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.nodejs20,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-15',
    slug: 'nodejs-20',
    namespace: 'default',
    name: 'Node.js 20',
    description: 'Previous LTS release, still running on some older services.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle_date: '2026-04-30',
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://endoflife.date/nodejs', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.nodejs],
      provider_product: 'nodejs',
      release_cycle: '20',
      latest_version: '20.19.0',
      release_date: '2023-04-18',
      active_support_until: '2024-10-22',
      security_support_until: '2026-04-30',
      eol_date: '2026-04-30',
      source_url: 'https://endoflife.date/nodejs',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.nodejs18,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-16',
    slug: 'nodejs-18',
    namespace: 'default',
    name: 'Node.js 18',
    description: 'End-of-life release retained on the books until the last consumers migrate.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://endoflife.date/nodejs', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.nodejs],
      provider_product: 'nodejs',
      release_cycle: '18',
      latest_version: '18.20.5',
      release_date: '2022-04-19',
      active_support_until: '2023-10-18',
      security_support_until: '2025-04-30',
      eol_date: '2025-04-30',
      source_url: 'https://endoflife.date/nodejs',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'hold'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.typescript54,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-2',
    slug: 'typescript-5-4',
    namespace: 'default',
    name: 'TypeScript 5.4',
    description: 'TypeScript 5.4 release cycle tracked for language support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'javascript'],
    links: [
      { url: 'https://endoflife.date/typescript', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.typescript],
      provider_product: 'typescript',
      release_cycle: '5.4',
      latest_version: '5.4.5',
      release_date: '2024-03-06',
      active_support_until: '2024-09-06',
      security_support_until: '2026-03-06',
      eol_date: '2026-03-06',
      source_url: 'https://endoflife.date/typescript',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.react19,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-3',
    slug: 'react-19',
    namespace: 'default',
    name: 'React 19',
    description: 'React 19 release cycle tracked for frontend support planning.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['framework', 'frontend'],
    links: [{ url: 'https://endoflife.date/react', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.react],
      provider_product: 'react',
      release_cycle: '19',
      latest_version: '19.0.0',
      release_date: '2024-12-05',
      active_support_until: '2025-12-05',
      security_support_until: '2027-12-05',
      eol_date: '2027-12-05',
      source_url: 'https://endoflife.date/react',
      last_synchronized: '2026-01-01',
      category: 'framework',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.go123,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-4',
    slug: 'go-1-23',
    namespace: 'default',
    name: 'Go 1.23',
    description: 'Go 1.23 release cycle tracked for runtime support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://endoflife.date/go', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.go],
      provider_product: 'go',
      release_cycle: '1.23',
      latest_version: '1.23.4',
      release_date: '2024-08-13',
      active_support_until: '2025-02-13',
      security_support_until: '2025-08-13',
      eol_date: '2025-08-13',
      source_url: 'https://endoflife.date/go',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.python313,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-5',
    slug: 'python-3-13',
    namespace: 'default',
    name: 'Python 3.13',
    description: 'Python 3.13 release cycle tracked for the data platform.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'data'],
    links: [{ url: 'https://endoflife.date/python', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.python],
      provider_product: 'python',
      release_cycle: '3.13',
      latest_version: '3.13.1',
      release_date: '2024-10-07',
      active_support_until: '2025-10-01',
      security_support_until: '2029-10-01',
      eol_date: '2029-10-01',
      source_url: 'https://endoflife.date/python',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.java21,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-6',
    slug: 'java-21',
    namespace: 'default',
    name: 'Java 21',
    description: 'Java 21 (LTS) release cycle tracked for the legacy ledger service.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'legacy'],
    links: [{ url: 'https://endoflife.date/java', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.java],
      provider_product: 'java',
      release_cycle: '21',
      latest_version: '21.0.5',
      release_date: '2023-09-19',
      active_support_until: '2025-09-19',
      security_support_until: '2031-09-19',
      eol_date: '2031-09-19',
      source_url: 'https://endoflife.date/java',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'hold'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.postgres16,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-7',
    slug: 'postgresql-16',
    namespace: 'default',
    name: 'PostgreSQL 16',
    description: 'PostgreSQL 16 release cycle tracked for database support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'managed'],
    links: [
      { url: 'https://endoflife.date/postgresql', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.postgresql],
      provider_product: 'postgresql',
      release_cycle: '16',
      latest_version: '16.6',
      release_date: '2023-09-14',
      active_support_until: '2025-09-14',
      security_support_until: '2028-11-09',
      eol_date: '2028-11-09',
      source_url: 'https://endoflife.date/postgresql',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.postgres15,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-17',
    slug: 'postgresql-15',
    namespace: 'default',
    name: 'PostgreSQL 15',
    description: 'Previous major release, still running the Notification Postgres cluster.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle_date: '2026-11-01',
    tags: ['database', 'managed'],
    links: [
      { url: 'https://endoflife.date/postgresql', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.postgresql],
      provider_product: 'postgresql',
      release_cycle: '15',
      latest_version: '15.10',
      release_date: '2022-10-13',
      active_support_until: '2024-10-13',
      security_support_until: '2027-11-11',
      eol_date: '2027-11-11',
      source_url: 'https://endoflife.date/postgresql',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.postgres14,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-18',
    slug: 'postgresql-14',
    namespace: 'default',
    name: 'PostgreSQL 14',
    description: 'End-of-life release retained on the books until the last consumers migrate.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'managed'],
    links: [
      { url: 'https://endoflife.date/postgresql', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.postgresql],
      provider_product: 'postgresql',
      release_cycle: '14',
      latest_version: '14.15',
      release_date: '2021-09-30',
      active_support_until: '2023-09-30',
      security_support_until: '2026-11-12',
      eol_date: '2026-11-12',
      source_url: 'https://endoflife.date/postgresql',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'hold'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.redis75,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-8',
    slug: 'redis-7-5',
    namespace: 'default',
    name: 'Redis 7.5',
    description: 'Redis 7.5 release cycle tracked for caching support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'cache'],
    links: [{ url: 'https://endoflife.date/redis', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.redis],
      provider_product: 'redis',
      release_cycle: '7.5',
      latest_version: '7.5.2',
      release_date: '2024-06-01',
      active_support_until: '2025-06-01',
      security_support_until: '2027-06-01',
      eol_date: '2027-06-01',
      source_url: 'https://endoflife.date/redis',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.kafka38,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-9',
    slug: 'kafka-3-8',
    namespace: 'default',
    name: 'Apache Kafka 3.8',
    description: 'Apache Kafka 3.8 release cycle tracked for the event backbone.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['messaging', 'managed'],
    links: [
      { url: 'https://endoflife.date/apache-kafka', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.kafka],
      provider_product: 'apache-kafka',
      release_cycle: '3.8',
      latest_version: '3.8.1',
      release_date: '2024-07-30',
      active_support_until: '2025-07-30',
      security_support_until: '2025-07-30',
      eol_date: '2025-07-30',
      source_url: 'https://endoflife.date/apache-kafka',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.elasticsearch815,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-10',
    slug: 'elasticsearch-8-15',
    namespace: 'default',
    name: 'Elasticsearch 8.15',
    description: 'Elasticsearch 8.15 release cycle tracked for the search platform.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-01',
    tags: ['database', 'search'],
    links: [
      { url: 'https://endoflife.date/elasticsearch', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.elasticsearch],
      provider_product: 'elasticsearch',
      release_cycle: '8.15',
      latest_version: '8.15.3',
      release_date: '2024-08-22',
      active_support_until: '2025-08-22',
      security_support_until: '2026-08-22',
      eol_date: '2026-08-22',
      source_url: 'https://endoflife.date/elasticsearch',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.rust182,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-11',
    slug: 'rust-1-82',
    namespace: 'default',
    name: 'Rust 1.82',
    description:
      'Rust 1.82 release cycle tracked as part of the payments authorization evaluation.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://endoflife.date/rust', title: 'Lifecycle source', type: 'source' }],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.rust],
      provider_product: 'rust',
      release_cycle: '1.82',
      latest_version: '1.82.0',
      release_date: '2024-10-17',
      active_support_until: '2025-04-17',
      security_support_until: '2025-04-17',
      eol_date: '2025-04-17',
      source_url: 'https://endoflife.date/rust',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.kubernetes130,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-12',
    slug: 'kubernetes-1-30',
    namespace: 'default',
    name: 'Kubernetes 1.30',
    description: 'Kubernetes 1.30 release cycle tracked for the payments cluster.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'infrastructure'],
    links: [
      { url: 'https://endoflife.date/kubernetes', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.kubernetes],
      provider_product: 'kubernetes',
      release_cycle: '1.30',
      latest_version: '1.30.6',
      release_date: '2024-04-17',
      active_support_until: '2025-06-28',
      security_support_until: '2025-06-28',
      eol_date: '2025-06-28',
      source_url: 'https://endoflife.date/kubernetes',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.kubernetes129,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-19',
    slug: 'kubernetes-1-29',
    namespace: 'default',
    name: 'Kubernetes 1.29',
    description: 'Previous release, still running one node pool in the payments cluster.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle_date: '2026-10-28',
    tags: ['runtime', 'infrastructure'],
    links: [
      { url: 'https://endoflife.date/kubernetes', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.kubernetes],
      provider_product: 'kubernetes',
      release_cycle: '1.29',
      latest_version: '1.29.10',
      release_date: '2023-12-13',
      active_support_until: '2025-02-28',
      security_support_until: '2025-02-28',
      eol_date: '2025-02-28',
      source_url: 'https://endoflife.date/kubernetes',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.kubernetes128,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-20',
    slug: 'kubernetes-1-28',
    namespace: 'default',
    name: 'Kubernetes 1.28',
    description: 'End-of-life release retained on the books until the last node pool migrates.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'infrastructure'],
    links: [
      { url: 'https://endoflife.date/kubernetes', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.kubernetes],
      provider_product: 'kubernetes',
      release_cycle: '1.28',
      latest_version: '1.28.15',
      release_date: '2023-08-15',
      active_support_until: '2024-10-28',
      security_support_until: '2024-10-28',
      eol_date: '2024-10-28',
      source_url: 'https://endoflife.date/kubernetes',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'hold'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.docker27,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-13',
    slug: 'docker-27',
    namespace: 'default',
    name: 'Docker 27',
    description: 'Docker 27 release cycle tracked for container tooling.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'infrastructure'],
    links: [
      { url: 'https://endoflife.date/docker-engine', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.docker],
      provider_product: 'docker-engine',
      release_cycle: '27',
      latest_version: '27.4.1',
      release_date: '2024-08-29',
      active_support_until: '2025-08-29',
      security_support_until: '2025-08-29',
      eol_date: '2025-08-29',
      source_url: 'https://endoflife.date/docker-engine',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: REL.snowflake,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-14',
    slug: 'snowflake-current',
    namespace: 'default',
    name: 'Snowflake (current)',
    description:
      'Snowflake current release tracked while under evaluation for the analytics warehouse.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'warehouse'],
    links: [
      { url: 'https://www.snowflake.com/en/support/', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: SEED_SCHEMA_IDS.technologyRelease,
    data: {
      technology: [T.snowflake],
      provider_product: 'snowflake',
      release_cycle: 'rolling',
      latest_version: '9.0',
      release_date: '2025-01-06',
      active_support_until: '2026-01-06',
      security_support_until: '2026-01-06',
      eol_date: '2026-01-06',
      source_url: 'https://www.snowflake.com/en/support/',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

const RES = DEMO_TECHNOLOGY_IDS.resources;
// System ids reused from the shared (non-demo) seed data.
const SYSTEMS = {
  customerPortal: '00000000-0000-0000-0002-000000000001',
  identityPlatform: '00000000-0000-0000-0002-000000000002',
  paymentsPlatform: '00000000-0000-0000-0002-000000000003',
  analyticsPlatform: '00000000-0000-0000-0002-000000000004',
  notificationHub: '00000000-0000-0000-0002-000000000005',
  searchPlatform: '00000000-0000-0000-0002-000000000006'
};

export const demoResourceEntities: SeedEntityInput[] = [
  {
    id: RES.postgresMain,
    workspace: WORKSPACE_ID,
    public_id: 'RES-1',
    slug: 'postgres-main',
    namespace: 'default',
    name: 'Postgres Main',
    description: 'Primary PostgreSQL cluster used by the Customer Portal system.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['postgres', 'managed'],
    links: [
      { url: 'https://grafana.example.com/d/postgres-main', title: 'Dashboard', type: 'dashboard' }
    ],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'database',
      technology_releases: [REL.postgres16],
      system: [SYSTEMS.customerPortal]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.redisCache,
    workspace: WORKSPACE_ID,
    public_id: 'RES-2',
    slug: 'redis-cache',
    namespace: 'default',
    name: 'Redis Cache',
    description: 'Session and response cache for the customer portal.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['redis', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'cache',
      technology_releases: [REL.redis75],
      system: [SYSTEMS.customerPortal]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.cdn,
    workspace: WORKSPACE_ID,
    public_id: 'RES-3',
    slug: 'cdn',
    namespace: 'default',
    name: 'CDN',
    description: 'Edge content delivery network fronting the customer portal.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cdn', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'cdn',
      system: [SYSTEMS.customerPortal]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.identitySessionCache,
    workspace: WORKSPACE_ID,
    public_id: 'RES-4',
    slug: 'identity-session-cache',
    namespace: 'default',
    name: 'Identity Session Cache',
    description: 'In-memory store for active sessions and token revocation lists.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['redis', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'cache',
      technology_releases: [REL.redis75],
      system: [SYSTEMS.identityPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.paymentsPostgres,
    workspace: WORKSPACE_ID,
    public_id: 'RES-5',
    slug: 'payments-postgres',
    namespace: 'default',
    name: 'Payments Postgres',
    description: 'Dedicated PostgreSQL cluster storing ledger and transaction state.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['postgres', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'database',
      technology_releases: [REL.postgres16],
      system: [SYSTEMS.paymentsPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.paymentsKubernetesCluster,
    workspace: WORKSPACE_ID,
    public_id: 'RES-6',
    slug: 'payments-kubernetes-cluster',
    namespace: 'default',
    name: 'Payments Kubernetes Cluster',
    description:
      'Dedicated Kubernetes cluster hosting the payment authorization and settlement services.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['kubernetes', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'compute-cluster',
      technology_releases: [REL.kubernetes130],
      system: [SYSTEMS.paymentsPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.s3DataLake,
    workspace: WORKSPACE_ID,
    public_id: 'RES-7',
    slug: 's3-data-lake',
    namespace: 'default',
    name: 'S3 Data Lake',
    description: 'Raw event storage feeding the analytics warehouse.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['s3', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'object-storage',
      system: [SYSTEMS.analyticsPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.analyticsWarehouse,
    workspace: WORKSPACE_ID,
    public_id: 'RES-8',
    slug: 'analytics-warehouse',
    namespace: 'default',
    name: 'Analytics Warehouse',
    description: 'Cloud data warehouse powering internal reporting, currently piloting Snowflake.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['warehouse', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'data-warehouse',
      technology_releases: [REL.snowflake],
      system: [SYSTEMS.analyticsPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.kafkaEventBus,
    workspace: WORKSPACE_ID,
    public_id: 'RES-9',
    slug: 'kafka-event-bus',
    namespace: 'default',
    name: 'Kafka Event Bus',
    description: 'Event backbone for order, notification and analytics event streams.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['kafka', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'message-queue',
      technology_releases: [REL.kafka38],
      system: [SYSTEMS.notificationHub]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.notificationPostgres,
    workspace: WORKSPACE_ID,
    public_id: 'RES-10',
    slug: 'notification-postgres',
    namespace: 'default',
    name: 'Notification Postgres',
    description:
      'PostgreSQL cluster storing notification templates, delivery state and webhook subscriptions.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['postgres', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'database',
      technology_releases: [REL.postgres16],
      system: [SYSTEMS.notificationHub]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.elasticsearchCluster,
    workspace: WORKSPACE_ID,
    public_id: 'RES-11',
    slug: 'elasticsearch-cluster',
    namespace: 'default',
    name: 'Elasticsearch Cluster',
    description: 'Search index backing the Search Platform.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['elasticsearch', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'search-index',
      technology_releases: [REL.elasticsearch815],
      system: [SYSTEMS.searchPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: RES.searchQueryCache,
    workspace: WORKSPACE_ID,
    public_id: 'RES-12',
    slug: 'search-query-cache',
    namespace: 'default',
    name: 'Search Query Cache',
    description: 'Cache for frequent search and recommendation queries.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['redis', 'managed'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.resource,
    data: {
      resource_type: 'cache',
      technology_releases: [REL.redis75],
      system: [SYSTEMS.searchPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];
