import type { SeedEntityInput } from './entities';
import {
  DEMO_ARCHITECTURE_IDS,
  DEMO_TECHNOLOGY_IDS,
  LIFECYCLE_IDS,
  SEED_SCHEMA_IDS,
  TEAM_IDS,
  WORKSPACE_ID,
  now
} from './constants';

// Additive Domain/System/Component/API/Data Entity rows for the demo dataset, filling the gap
// between the strategy tree's catalog/order/marketing capabilities (demoStrategyEntities.ts) and
// the architecture graph, which otherwise only covers customer portal/identity/payments/analytics/
// notifications/search. These are added ALONGSIDE the test dataset's rows (see the comment on
// DEMO_ARCHITECTURE_IDS in constants.ts for why), continuing the public_id numbering from DOM-4,
// SYS-7, CMP-17, API-7, DE-4.
const D = DEMO_ARCHITECTURE_IDS.domains;
const S = DEMO_ARCHITECTURE_IDS.systems;
const C = DEMO_ARCHITECTURE_IDS.components;
const A = DEMO_ARCHITECTURE_IDS.apis;
const DE = DEMO_ARCHITECTURE_IDS.dataEntities;
const REL = DEMO_TECHNOLOGY_IDS.releases;

export const demoDomainEntities: SeedEntityInput[] = [
  {
    id: D.catalogMerchandising,
    workspace: WORKSPACE_ID,
    public_id: 'DOM-4',
    slug: 'catalog-and-merchandising',
    namespace: 'default',
    name: 'Catalog & Merchandising',
    description: 'Product information, pricing and merchandising systems for the storefront.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.domain,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: D.orderFulfillmentSupplyChain,
    workspace: WORKSPACE_ID,
    public_id: 'DOM-5',
    slug: 'order-fulfillment-and-supply-chain',
    namespace: 'default',
    name: 'Order Fulfillment & Supply Chain',
    description: 'Order management, inventory and shipping systems from checkout to delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.domain,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: D.marketingGrowth,
    workspace: WORKSPACE_ID,
    public_id: 'DOM-6',
    slug: 'marketing-and-growth',
    namespace: 'default',
    name: 'Marketing & Growth',
    description: 'Campaign, promotion and personalization systems driving customer acquisition.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.domain,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoSystemEntities: SeedEntityInput[] = [
  {
    id: S.productCatalogService,
    workspace: WORKSPACE_ID,
    public_id: 'SYS-7',
    slug: 'product-catalog-service',
    namespace: 'default',
    name: 'Product Catalog Service',
    description: 'Owns product, variant and pricing data for the storefront and search.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-1', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.system,
    data: { domain: [D.catalogMerchandising] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: S.orderManagementSystem,
    workspace: WORKSPACE_ID,
    public_id: 'SYS-8',
    slug: 'order-management-system',
    namespace: 'default',
    name: 'Order Management System',
    description: 'Orchestrates order capture, inventory allocation and fulfillment handoff.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-0', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.system,
    data: { domain: [D.orderFulfillmentSupplyChain] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: S.fulfillmentLogisticsPlatform,
    workspace: WORKSPACE_ID,
    public_id: 'SYS-9',
    slug: 'fulfillment-and-logistics-platform',
    namespace: 'default',
    name: 'Fulfillment & Logistics Platform',
    description: 'Warehouse operations and carrier integration for outbound shipments.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-1', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.system,
    data: { domain: [D.orderFulfillmentSupplyChain] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: S.marketingAutomationPlatform,
    workspace: WORKSPACE_ID,
    public_id: 'SYS-10',
    slug: 'marketing-automation-platform',
    namespace: 'default',
    name: 'Marketing Automation Platform',
    description: 'Campaign orchestration, promotions and on-site personalization.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-1', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.system,
    data: { domain: [D.marketingGrowth] },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoComponentEntities: SeedEntityInput[] = [
  {
    id: C.catalogService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-17',
    slug: 'catalog-service',
    namespace: 'default',
    name: 'Catalog Service',
    description: 'Serves product and variant data to the storefront and downstream consumers.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.go123],
      system: [S.productCatalogService],
      provides_apis: [A.catalogApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.pricingEngine,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-18',
    slug: 'pricing-engine',
    namespace: 'default',
    name: 'Pricing Engine',
    description: 'Computes list and promotional prices from catalog and promotion rules.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.python313],
      system: [S.productCatalogService],
      consumes_apis: [A.catalogApi, A.marketingApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.catalogSyncWorker,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-19',
    slug: 'catalog-sync-worker',
    namespace: 'default',
    name: 'Catalog Sync Worker',
    description: 'Batch job syncing supplier product feeds into the catalog service.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.python313],
      system: [S.productCatalogService],
      depends_on: [C.catalogService]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.orderOrchestrator,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-20',
    slug: 'order-orchestrator',
    namespace: 'default',
    name: 'Order Orchestrator',
    description: 'Coordinates order capture, payment authorization and fulfillment handoff.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['nodejs', 'tier-0'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.nodejs22],
      system: [S.orderManagementSystem],
      provides_apis: [A.orderApi],
      consumes_apis: [A.catalogApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.inventoryService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-21',
    slug: 'inventory-service',
    namespace: 'default',
    name: 'Inventory Service',
    description: 'Tracks stock levels and reservations across warehouses.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.go123],
      system: [S.orderManagementSystem],
      provides_apis: [A.inventoryApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.shippingIntegrationService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-22',
    slug: 'shipping-integration-service',
    namespace: 'default',
    name: 'Shipping Integration Service',
    description: 'Integrates with carrier APIs to generate labels and track shipments.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.go123],
      system: [S.fulfillmentLogisticsPlatform],
      provides_apis: [A.shippingApi],
      consumes_apis: [A.orderApi, A.inventoryApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.warehouseManagementService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-23',
    slug: 'warehouse-management-service',
    namespace: 'default',
    name: 'Warehouse Management Service',
    description: 'Manages pick, pack and stock movement workflows inside the warehouse.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-12-01',
    tags: ['java', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.java21],
      system: [S.fulfillmentLogisticsPlatform],
      consumes_apis: [A.inventoryApi],
      depends_on: [C.shippingIntegrationService]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.campaignService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-24',
    slug: 'campaign-service',
    namespace: 'default',
    name: 'Campaign Service',
    description: 'Schedules and executes marketing campaigns across email and push channels.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['nodejs', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.nodejs22],
      system: [S.marketingAutomationPlatform],
      provides_apis: [A.marketingApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.promotionsEngine,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-25',
    slug: 'promotions-engine',
    namespace: 'default',
    name: 'Promotions Engine',
    description: 'Evaluates and applies discount and promotion rules at checkout.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['typescript', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [DEMO_TECHNOLOGY_IDS.releases.typescript54],
      system: [S.marketingAutomationPlatform],
      consumes_apis: [A.catalogApi, A.marketingApi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: C.personalizationService,
    workspace: WORKSPACE_ID,
    public_id: 'CMP-26',
    slug: 'personalization-service',
    namespace: 'default',
    name: 'Personalization Service',
    description: 'Generates personalised recommendations and offers from behavioural data.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.proposed,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.component,
    data: {
      technology_releases: [REL.python313],
      system: [S.marketingAutomationPlatform],
      consumes_apis: [A.marketingApi],
      depends_on: [C.campaignService]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoApiEntities: SeedEntityInput[] = [
  {
    id: A.catalogApi,
    workspace: WORKSPACE_ID,
    public_id: 'API-7',
    slug: 'catalog-api',
    namespace: 'default',
    name: 'Catalog API',
    description: 'REST API exposing product, variant and pricing data.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'catalog'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.api,
    data: { api_type: 'openapi', protocols: ['https-rest'], system: [S.productCatalogService] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: A.orderApi,
    workspace: WORKSPACE_ID,
    public_id: 'API-8',
    slug: 'order-api',
    namespace: 'default',
    name: 'Order API',
    description: 'REST API for order capture and status.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.api,
    data: { api_type: 'openapi', protocols: ['https-rest'], system: [S.orderManagementSystem] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: A.inventoryApi,
    workspace: WORKSPACE_ID,
    public_id: 'API-9',
    slug: 'inventory-api',
    namespace: 'default',
    name: 'Inventory API',
    description: 'gRPC API for stock level queries and reservations.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['grpc', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.api,
    data: { api_type: 'grpc', protocols: ['grpc'], system: [S.orderManagementSystem] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: A.shippingApi,
    workspace: WORKSPACE_ID,
    public_id: 'API-10',
    slug: 'shipping-api',
    namespace: 'default',
    name: 'Shipping API',
    description: 'REST API for label generation and shipment tracking.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'fulfillment'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.api,
    data: {
      api_type: 'openapi',
      protocols: ['https-rest'],
      system: [S.fulfillmentLogisticsPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: A.marketingApi,
    workspace: WORKSPACE_ID,
    public_id: 'API-11',
    slug: 'marketing-api',
    namespace: 'default',
    name: 'Marketing API',
    description: 'Event-driven API for campaign, promotion and personalization events.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['asyncapi', 'marketing'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.api,
    data: {
      api_type: 'asyncapi',
      protocols: ['kafka', 'https-rest'],
      system: [S.marketingAutomationPlatform]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoDataEntityEntities: SeedEntityInput[] = [
  {
    id: DE.productCatalogData,
    workspace: WORKSPACE_ID,
    public_id: 'DE-4',
    slug: 'product-catalog-data',
    namespace: 'default',
    name: 'Product Catalog Data',
    description: 'Product, variant and pricing records powering the storefront and search.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: SEED_SCHEMA_IDS.dataEntity,
    data: { classification: 'non-sensitive' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DE.orderRecords,
    workspace: WORKSPACE_ID,
    public_id: 'DE-5',
    slug: 'order-records',
    namespace: 'default',
    name: 'Order Records',
    description: 'Order line items, customer and shipping details captured at checkout.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: SEED_SCHEMA_IDS.dataEntity,
    data: {
      classification: 'sensitive',
      regulatory_tags: ['pci-dss'],
      processing_purposes: ['fraud-prevention']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DE.inventoryLevels,
    workspace: WORKSPACE_ID,
    public_id: 'DE-6',
    slug: 'inventory-levels',
    namespace: 'default',
    name: 'Inventory Levels',
    description: 'Stock-on-hand and reservation counts per warehouse and SKU.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: SEED_SCHEMA_IDS.dataEntity,
    data: { classification: 'non-sensitive' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DE.marketingConsentRecords,
    workspace: WORKSPACE_ID,
    public_id: 'DE-7',
    slug: 'marketing-consent-records',
    namespace: 'default',
    name: 'Marketing Consent Records',
    description: 'Customer opt-in/opt-out preferences for marketing communications.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: SEED_SCHEMA_IDS.dataEntity,
    data: { classification: 'sensitive', regulatory_tags: ['gdpr'] },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];
