import type { SeedEntityInput } from './entities';
import {
  DEMO_BUSINESS_CAPABILITY_IDS,
  DEMO_STRATEGY_GOAL_IDS,
  LIFECYCLE_IDS,
  STRATEGY_IDS,
  TEAM_IDS,
  WORKSPACE_ID,
  now
} from './constants';

// The "demo" bootstrap dataset's Business Capability tree: a three-level capability map for an
// online retailer / e-commerce business (see #3020 follow-up). Loaded only when `pnpm bootstrap`
// is run with `--dataset demo` (the default) - the original 5-capability tree in
// `seedStrategyEntities` (entities.ts) remains the "test" dataset that seedData.test.ts asserts on
// and that every other programmatic caller of seedBootstrapData keeps using by default.
export const demoBusinessCapabilityEntities: SeedEntityInput[] = [
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.merchandisingAssortment,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-1',
    slug: 'merchandising-and-assortment',
    namespace: 'default',
    name: 'Merchandising & Assortment',
    description:
      'Group of related second-level capabilities supporting merchandising & assortment.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting merchandising & assortment.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.marketingCustomerAcquisition,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-2',
    slug: 'marketing-and-customer-acquisition',
    namespace: 'default',
    name: 'Marketing & Customer Acquisition',
    description:
      'Group of related second-level capabilities supporting marketing & customer acquisition.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'acquisition'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting marketing & customer acquisition.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.salesCommerceExperience,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-3',
    slug: 'sales-and-commerce-experience',
    namespace: 'default',
    name: 'Sales & Commerce Experience',
    description:
      'Group of related second-level capabilities supporting sales & commerce experience.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'commerce'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting sales & commerce experience.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.orderFulfillmentLogistics,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-4',
    slug: 'order-fulfillment-and-logistics',
    namespace: 'default',
    name: 'Order Fulfillment & Logistics',
    description:
      'Group of related second-level capabilities supporting order fulfillment & logistics.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'logistics'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting order fulfillment & logistics.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.customerServiceSupport,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-5',
    slug: 'customer-service-and-support',
    namespace: 'default',
    name: 'Customer Service & Support',
    description:
      'Group of related second-level capabilities supporting customer service & support.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer-service', 'support'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting customer service & support.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.supplyChainVendorManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-6',
    slug: 'supply-chain-and-vendor-management',
    namespace: 'default',
    name: 'Supply Chain & Vendor Management',
    description:
      'Group of related second-level capabilities supporting supply chain & vendor management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'vendors'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting supply chain & vendor management.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.financePayments,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-7',
    slug: 'finance-and-payments',
    namespace: 'default',
    name: 'Finance & Payments',
    description: 'Group of related second-level capabilities supporting finance & payments.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['finance', 'payments'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Group of related second-level capabilities supporting finance & payments.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.platformReliabilityOperations,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-8',
    slug: 'platform-reliability-and-operations',
    namespace: 'default',
    name: 'Platform Reliability & Operations',
    description:
      'Group of related second-level capabilities supporting platform reliability & operations.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'reliability'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description:
        'Group of related second-level capabilities supporting platform reliability & operations.',
      parent: [],
      target_date: '2027-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.productCatalogManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-9',
    slug: 'product-catalog-management',
    namespace: 'default',
    name: 'Product Catalog Management',
    description: 'Ability to product catalog management across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'catalog'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to product catalog management across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.merchandisingAssortment],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.pricingPromotions,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-10',
    slug: 'pricing-and-promotions',
    namespace: 'default',
    name: 'Pricing & Promotions',
    description: 'Ability to pricing & promotions across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'pricing'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to pricing & promotions across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.merchandisingAssortment],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.digitalMarketing,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-11',
    slug: 'digital-marketing',
    namespace: 'default',
    name: 'Digital Marketing',
    description: 'Ability to digital marketing across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'digital'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to digital marketing across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.marketingCustomerAcquisition],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.customerEngagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-12',
    slug: 'customer-engagement',
    namespace: 'default',
    name: 'Customer Engagement',
    description: 'Ability to customer engagement across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'engagement'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to customer engagement across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.marketingCustomerAcquisition],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.storefrontExperience,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-13',
    slug: 'storefront-experience',
    namespace: 'default',
    name: 'Storefront Experience',
    description: 'Ability to storefront experience across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'storefront'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to storefront experience across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.salesCommerceExperience],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.cartCheckout,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-14',
    slug: 'cart-and-checkout',
    namespace: 'default',
    name: 'Cart & Checkout',
    description: 'Ability to cart & checkout across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'checkout'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to cart & checkout across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.salesCommerceExperience],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.orderManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-15',
    slug: 'order-management',
    namespace: 'default',
    name: 'Order Management',
    description: 'Ability to order management across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'orders'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to order management across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.orderFulfillmentLogistics],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.warehouseDelivery,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-16',
    slug: 'warehouse-and-delivery',
    namespace: 'default',
    name: 'Warehouse & Delivery',
    description: 'Ability to warehouse & delivery across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'warehouse'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to warehouse & delivery across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.orderFulfillmentLogistics],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.customerCareOperations,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-17',
    slug: 'customer-care-operations',
    namespace: 'default',
    name: 'Customer Care Operations',
    description: 'Ability to customer care operations across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['support', 'care'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to customer care operations across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.customerServiceSupport],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.selfServiceManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-18',
    slug: 'self-service-management',
    namespace: 'default',
    name: 'Self-Service Management',
    description: 'Ability to self-service management across the retail business.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['support', 'self-service'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to self-service management across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.customerServiceSupport],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.supplierManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-19',
    slug: 'supplier-management',
    namespace: 'default',
    name: 'Supplier Management',
    description: 'Ability to supplier management across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'suppliers'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to supplier management across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.supplyChainVendorManagement],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.procurementDemandPlanning,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-20',
    slug: 'procurement-and-demand-planning',
    namespace: 'default',
    name: 'Procurement & Demand Planning',
    description: 'Ability to procurement & demand planning across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'procurement'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to procurement & demand planning across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.supplyChainVendorManagement],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.paymentsManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-21',
    slug: 'payments-management',
    namespace: 'default',
    name: 'Payments Management',
    description: 'Ability to payments management across the retail business.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to payments management across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.financePayments],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.financialOperations,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-22',
    slug: 'financial-operations',
    namespace: 'default',
    name: 'Financial Operations',
    description: 'Ability to financial operations across the retail business.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['finance'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to financial operations across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.financePayments],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.platformReliability,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-23',
    slug: 'platform-reliability',
    namespace: 'default',
    name: 'Platform Reliability',
    description: 'Ability to platform reliability across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'reliability'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to platform reliability across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.platformReliabilityOperations],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.dataAnalyticsPlatform,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-24',
    slug: 'data-and-analytics-platform',
    namespace: 'default',
    name: 'Data & Analytics Platform',
    description: 'Ability to data & analytics platform across the retail business.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'data'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Ability to data & analytics platform across the retail business.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.platformReliabilityOperations],
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.productInformationManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-25',
    slug: 'product-information-management',
    namespace: 'default',
    name: 'Product Information Management',
    description: 'Specific operational capability delivering product information management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['catalog', 'pim'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering product information management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.productCatalogManagement],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.digitalAssetManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-26',
    slug: 'digital-asset-management',
    namespace: 'default',
    name: 'Digital Asset Management',
    description: 'Specific operational capability delivering digital asset management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['catalog', 'dam'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering digital asset management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.productCatalogManagement],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.promotionDiscountManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-27',
    slug: 'promotion-and-discount-management',
    namespace: 'default',
    name: 'Promotion & Discount Management',
    description: 'Specific operational capability delivering promotion & discount management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['pricing', 'promotions'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering promotion & discount management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.pricingPromotions],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.campaignManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-28',
    slug: 'campaign-management',
    namespace: 'default',
    name: 'Campaign Management',
    description: 'Specific operational capability delivering campaign management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'campaigns'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering campaign management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.digitalMarketing],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.seoContentMarketing,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-29',
    slug: 'seo-and-content-marketing',
    namespace: 'default',
    name: 'SEO & Content Marketing',
    description: 'Specific operational capability delivering seo & content marketing.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'seo'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering seo & content marketing.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.digitalMarketing],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.loyaltyRewardsManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-30',
    slug: 'loyalty-and-rewards-management',
    namespace: 'default',
    name: 'Loyalty & Rewards Management',
    description: 'Specific operational capability delivering loyalty & rewards management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['engagement', 'loyalty'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering loyalty & rewards management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.customerEngagement],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.personalizationRecommendations,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-31',
    slug: 'personalization-and-recommendations',
    namespace: 'default',
    name: 'Personalization & Recommendations',
    description: 'Specific operational capability delivering personalization & recommendations.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['engagement', 'personalization'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering personalization & recommendations.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.customerEngagement],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.siteMerchandising,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-32',
    slug: 'site-merchandising',
    namespace: 'default',
    name: 'Site Merchandising',
    description: 'Specific operational capability delivering site merchandising.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['storefront', 'merchandising'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering site merchandising.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.storefrontExperience],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.searchNavigation,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-33',
    slug: 'search-and-navigation',
    namespace: 'default',
    name: 'Search & Navigation',
    description: 'Specific operational capability delivering search & navigation.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['storefront', 'search'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering search & navigation.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.storefrontExperience],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.checkoutOrchestration,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-34',
    slug: 'checkout-orchestration',
    namespace: 'default',
    name: 'Checkout Orchestration',
    description: 'Specific operational capability delivering checkout orchestration.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['checkout'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering checkout orchestration.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.cartCheckout],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.orderOrchestration,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-35',
    slug: 'order-orchestration',
    namespace: 'default',
    name: 'Order Orchestration',
    description: 'Specific operational capability delivering order orchestration.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['orders'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering order orchestration.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.orderManagement],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.returnsRefundsManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-36',
    slug: 'returns-and-refunds-management',
    namespace: 'default',
    name: 'Returns & Refunds Management',
    description: 'Specific operational capability delivering returns & refunds management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['orders', 'returns'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering returns & refunds management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.orderManagement],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.inventoryWarehouseManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-37',
    slug: 'inventory-and-warehouse-management',
    namespace: 'default',
    name: 'Inventory & Warehouse Management',
    description: 'Specific operational capability delivering inventory & warehouse management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['warehouse', 'inventory'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering inventory & warehouse management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.warehouseDelivery],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.shippingLastMileDelivery,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-38',
    slug: 'shipping-and-last-mile-delivery',
    namespace: 'default',
    name: 'Shipping & Last-Mile Delivery',
    description: 'Specific operational capability delivering shipping & last-mile delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['warehouse', 'shipping'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering shipping & last-mile delivery.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.warehouseDelivery],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.contactCenterManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-39',
    slug: 'contact-center-management',
    namespace: 'default',
    name: 'Contact Center Management',
    description: 'Specific operational capability delivering contact center management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['support', 'contact-center'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering contact center management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.customerCareOperations],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.accountManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-40',
    slug: 'account-management',
    namespace: 'default',
    name: 'Account Management',
    description: 'Specific operational capability delivering account management.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['support', 'accounts'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering account management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.selfServiceManagement],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.orderTrackingSelfService,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-41',
    slug: 'order-tracking-self-service',
    namespace: 'default',
    name: 'Order Tracking Self-Service',
    description: 'Specific operational capability delivering order tracking self-service.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['support', 'order-tracking'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering order tracking self-service.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.selfServiceManagement],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.supplierOnboarding,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-42',
    slug: 'supplier-onboarding',
    namespace: 'default',
    name: 'Supplier Onboarding',
    description: 'Specific operational capability delivering supplier onboarding.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['suppliers', 'onboarding'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering supplier onboarding.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.supplierManagement],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.supplierPerformanceManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-43',
    slug: 'supplier-performance-management',
    namespace: 'default',
    name: 'Supplier Performance Management',
    description: 'Specific operational capability delivering supplier performance management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['suppliers', 'performance'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering supplier performance management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.supplierManagement],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.purchaseOrderManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-44',
    slug: 'purchase-order-management',
    namespace: 'default',
    name: 'Purchase Order Management',
    description: 'Specific operational capability delivering purchase order management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['procurement'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering purchase order management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.procurementDemandPlanning],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.paymentProcessing,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-45',
    slug: 'payment-processing',
    namespace: 'default',
    name: 'Payment Processing',
    description: 'Specific operational capability delivering payment processing.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'processing'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering payment processing.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.paymentsManagement],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.fraudRiskManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-46',
    slug: 'fraud-and-risk-management',
    namespace: 'default',
    name: 'Fraud & Risk Management',
    description: 'Specific operational capability delivering fraud & risk management.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'fraud'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering fraud & risk management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.paymentsManagement],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.billingInvoicing,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-47',
    slug: 'billing-and-invoicing',
    namespace: 'default',
    name: 'Billing & Invoicing',
    description: 'Specific operational capability delivering billing & invoicing.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['finance', 'billing'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering billing & invoicing.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.financialOperations],
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.observabilityManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-48',
    slug: 'observability-management',
    namespace: 'default',
    name: 'Observability Management',
    description: 'Specific operational capability delivering observability management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'observability'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering observability management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.platformReliability],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.incidentProblemManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-49',
    slug: 'incident-and-problem-management',
    namespace: 'default',
    name: 'Incident & Problem Management',
    description: 'Specific operational capability delivering incident & problem management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'incident'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering incident & problem management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.platformReliability],
      target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_BUSINESS_CAPABILITY_IDS.dataPlatformManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-50',
    slug: 'data-platform-management',
    namespace: 'default',
    name: 'Data Platform Management',
    description: 'Specific operational capability delivering data platform management.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'data'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Specific operational capability delivering data platform management.',
      parent: [DEMO_BUSINESS_CAPABILITY_IDS.dataAnalyticsPlatform],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

// The demo dataset's Objective -> Outcome -> Initiative -> Measure chains, each supporting one
// demo Business Capability (wired via the objective-supports-business-capability relation in
// demoStrategyRelations.ts). Replaces the 2 test-dataset chains, same as demoBusinessCapabilityEntities
// replaces the test-dataset capabilities above.
export const demoObjectiveEntities: SeedEntityInput[] = [
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.expandProductAssortment,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-1',
    slug: 'expand-product-assortment',
    namespace: 'default',
    name: 'Expand Product Assortment',
    description: 'Grow the breadth of the product catalog across categories.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'catalog'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Grow the number of active SKUs by onboarding new sellers and brands.',
      status: 'active',
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.growNewCustomerAcquisition,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-2',
    slug: 'grow-new-customer-acquisition',
    namespace: 'default',
    name: 'Grow New Customer Acquisition',
    description: 'Increase the rate of new customers acquired through digital channels.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'acquisition'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Scale performance marketing spend into new customer segments.',
      status: 'active',
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.increaseCheckoutConversion,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-3',
    slug: 'increase-checkout-conversion',
    namespace: 'default',
    name: 'Increase Checkout Conversion',
    description: 'Reduce friction in the checkout flow to convert more carts into orders.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'checkout'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Simplify checkout steps and reduce cart abandonment.',
      status: 'active',
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.reduceDeliveryTime,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-4',
    slug: 'reduce-delivery-time',
    namespace: 'default',
    name: 'Reduce Delivery Time',
    description: 'Shorten the time from order placement to delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'logistics'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Expand regional fulfillment capacity to shorten delivery windows.',
      status: 'active',
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.improveSupplierOnTimeDelivery,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-5',
    slug: 'improve-supplier-on-time-delivery',
    namespace: 'default',
    name: 'Improve Supplier On-Time Delivery',
    description: 'Increase the share of supplier shipments that arrive on schedule.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'suppliers'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Hold suppliers accountable to delivery commitments through scorecards.',
      status: 'active',
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.objectives.reducePaymentFraudLosses,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-6',
    slug: 'reduce-payment-fraud-losses',
    namespace: 'default',
    name: 'Reduce Payment Fraud Losses',
    description: 'Lower losses attributable to fraudulent payment transactions.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'fraud'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Deploy real-time fraud detection across payment flows.',
      status: 'active',
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoOutcomeEntities: SeedEntityInput[] = [
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.increaseCatalogBreadth,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-1',
    slug: 'increase-catalog-breadth',
    namespace: 'default',
    name: 'Increase Catalog Breadth',
    description: 'The active product catalog grows across categories.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'catalog'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Catalog breadth increases as new sellers and brands onboard.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.expandProductAssortment]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.increaseNewCustomerSignups,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-2',
    slug: 'increase-new-customer-signups',
    namespace: 'default',
    name: 'Increase New Customer Signups',
    description: 'More new customers sign up each month.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'acquisition'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'New customer signups grow as marketing reach expands.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.growNewCustomerAcquisition]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.reduceCartAbandonmentRate,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-3',
    slug: 'reduce-cart-abandonment-rate',
    namespace: 'default',
    name: 'Reduce Cart Abandonment Rate',
    description: 'Fewer shoppers abandon their cart before completing checkout.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'checkout'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Cart abandonment declines as checkout friction is removed.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.increaseCheckoutConversion]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.shortenAverageDeliveryWindow,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-4',
    slug: 'shorten-average-delivery-window',
    namespace: 'default',
    name: 'Shorten Average Delivery Window',
    description: 'Orders arrive faster on average.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'logistics'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Average delivery time shrinks as regional capacity expands.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.reduceDeliveryTime]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.increaseSupplierOnTimeRate,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-5',
    slug: 'increase-supplier-on-time-rate',
    namespace: 'default',
    name: 'Increase Supplier On-Time Rate',
    description: 'More supplier shipments arrive on or before their committed date.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'suppliers'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Supplier on-time delivery improves as scorecards drive accountability.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.improveSupplierOnTimeDelivery]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.outcomes.lowerFraudLossRate,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-6',
    slug: 'lower-fraud-loss-rate',
    namespace: 'default',
    name: 'Lower Fraud Loss Rate',
    description: 'Losses from fraudulent transactions decline as a share of revenue.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'fraud'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Fraud loss rate declines as real-time detection rolls out.',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.reducePaymentFraudLosses]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoInitiativeEntities: SeedEntityInput[] = [
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.marketplaceSellerOnboarding,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-1',
    slug: 'marketplace-seller-onboarding',
    namespace: 'default',
    name: 'Marketplace Seller Onboarding',
    description: 'Build self-service tooling for third-party sellers to list products.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'catalog'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Self-service seller onboarding to widen the product catalog.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.expandProductAssortment],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseCatalogBreadth]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.performanceMarketingExpansion,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-2',
    slug: 'performance-marketing-expansion',
    namespace: 'default',
    name: 'Performance Marketing Expansion',
    description: 'Expand paid acquisition channels into new customer segments.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'acquisition'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Scale paid campaigns to reach new customer segments.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.growNewCustomerAcquisition],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseNewCustomerSignups]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.checkoutFlowSimplification,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-3',
    slug: 'checkout-flow-simplification',
    namespace: 'default',
    name: 'Checkout Flow Simplification',
    description: 'Reduce the number of steps and fields required to complete checkout.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'checkout'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Redesign checkout to a streamlined single-page flow.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.increaseCheckoutConversion],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.reduceCartAbandonmentRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.regionalFulfillmentCenterExpansion,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-4',
    slug: 'regional-fulfillment-center-expansion',
    namespace: 'default',
    name: 'Regional Fulfillment Center Expansion',
    description: 'Open additional regional fulfillment centers closer to customers.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'logistics'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Expand regional fulfillment capacity to cut delivery distance.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.reduceDeliveryTime],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.shortenAverageDeliveryWindow]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.supplierScorecardProgram,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-5',
    slug: 'supplier-scorecard-program',
    namespace: 'default',
    name: 'Supplier Scorecard Program',
    description: 'Score suppliers on delivery performance and share results quarterly.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'suppliers'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Quarterly supplier scorecards drive on-time delivery accountability.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.improveSupplierOnTimeDelivery],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseSupplierOnTimeRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.initiatives.realTimeFraudDetectionRollout,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-6',
    slug: 'real-time-fraud-detection-rollout',
    namespace: 'default',
    name: 'Real-Time Fraud Detection Rollout',
    description: 'Deploy machine-learning fraud scoring at time of payment.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'fraud'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Real-time scoring blocks fraudulent transactions before they settle.',
      status: 'active',
      objectives: [DEMO_STRATEGY_GOAL_IDS.objectives.reducePaymentFraudLosses],
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.lowerFraudLossRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoMeasureEntities: SeedEntityInput[] = [
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.activeSkuCount,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-1',
    slug: 'active-sku-count',
    namespace: 'default',
    name: 'Active SKU Count',
    description: 'Number of active, purchasable SKUs in the catalog.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['merchandising', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from the product catalog service.',
      unit: 'SKUs',
      target_value: 250000,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseCatalogBreadth]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.monthlyNewCustomerSignups,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-2',
    slug: 'monthly-new-customer-signups',
    namespace: 'default',
    name: 'Monthly New Customer Signups',
    description: 'Number of new customer accounts created per month.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['marketing', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked monthly from account creation events.',
      unit: 'signups',
      target_value: 50000,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseNewCustomerSignups]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.cartAbandonmentRate,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-3',
    slug: 'cart-abandonment-rate',
    namespace: 'default',
    name: 'Cart Abandonment Rate',
    description: 'Percentage of started checkouts that do not complete.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['sales', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from checkout funnel analytics.',
      unit: '%',
      target_value: 60,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.reduceCartAbandonmentRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.averageDeliveryDays,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-4',
    slug: 'average-delivery-days',
    namespace: 'default',
    name: 'Average Delivery Days',
    description: 'Average number of days from order placement to delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['fulfillment', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from order and shipment timestamps.',
      unit: 'days',
      target_value: 2,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.shortenAverageDeliveryWindow]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.supplierOnTimeDeliveryRate,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-5',
    slug: 'supplier-on-time-delivery-rate',
    namespace: 'default',
    name: 'Supplier On-Time Delivery Rate',
    description: 'Percentage of supplier shipments received on or before the committed date.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['supply-chain', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from supplier purchase order receipt data.',
      unit: '%',
      target_value: 95,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.increaseSupplierOnTimeRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_STRATEGY_GOAL_IDS.measures.fraudLossRate,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-6',
    slug: 'fraud-loss-rate',
    namespace: 'default',
    name: 'Fraud Loss Rate',
    description: 'Confirmed fraud losses as a percentage of gross merchandise value.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from confirmed chargebacks and fraud claims.',
      unit: '%',
      target_value: 0.1,
      outcomes: [DEMO_STRATEGY_GOAL_IDS.outcomes.lowerFraudLossRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];
