import type { SeedEntityInput } from './entities';
import {
  DEMO_RETENTION_IDS,
  DEMO_RISK_COMPLIANCE_IDS,
  LIFECYCLE_IDS,
  RETENTION_IDS,
  SEED_SCHEMA_IDS,
  TEAM_IDS,
  WORKSPACE_ID,
  now
} from './constants';

// The demo bootstrap dataset's governance content: Framework -> Compliance Requirement (via the
// requirement's `framework` containment field) <- Control (via the control-requirement relation,
// see demoGovernanceRelations.ts) <- Risk (via the risk-control relation). Replaces the 3
// Frameworks/Requirements/Controls/Risks in seedRiskComplianceEntities (entities.ts) for the demo
// dataset, themed around an online retailer handling payments and customer data.
export const demoFrameworkEntities: SeedEntityInput[] = [
  {
    id: DEMO_RISK_COMPLIANCE_IDS.frameworks.soc2TypeIi,
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-1',
    slug: 'soc-2-type-ii',
    namespace: 'default',
    name: 'SOC 2 Type II',
    description: 'Trust Services Criteria for security, availability, and confidentiality.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'audit'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.framework,
    data: { framework_kind: 'soc2', description: 'Annual SOC 2 Type II audit cycle.' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.frameworks.iso27001,
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-2',
    slug: 'iso-27001',
    namespace: 'default',
    name: 'ISO 27001',
    description: 'International standard for information security management systems.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'audit'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.framework,
    data: { framework_kind: 'iso27001', description: 'ISMS certification, renewed annually.' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.frameworks.pciDss,
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-3',
    slug: 'pci-dss',
    namespace: 'default',
    name: 'PCI DSS',
    description: 'Payment Card Industry Data Security Standard for handling cardholder data.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'payments'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.framework,
    data: {
      framework_kind: 'custom',
      description: 'Annual PCI DSS assessment for card payment flows.'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.frameworks.gdpr,
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-4',
    slug: 'gdpr',
    namespace: 'default',
    name: 'GDPR',
    description: 'EU General Data Protection Regulation for customer personal data.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'privacy'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.framework,
    data: {
      framework_kind: 'custom',
      description: 'Ongoing compliance program for EU customer personal data.'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoComplianceRequirementEntities: SeedEntityInput[] = [
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.soc2LogicalAccess,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-1',
    slug: 'soc2-cc6-1-logical-access',
    namespace: 'default',
    name: 'CC6.1 Logical Access Controls',
    description: 'Restricts logical access to authorized users and processes.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'CC6.1',
      description: 'The entity implements logical access security measures.',
      status: 'met',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.soc2TypeIi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.soc2SystemMonitoring,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-2',
    slug: 'soc2-cc7-2-monitoring',
    namespace: 'default',
    name: 'CC7.2 System Monitoring',
    description: 'Monitors system components for anomalies indicative of security events.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'CC7.2',
      description: 'The entity monitors system components for anomalous behavior.',
      status: 'in-progress',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.soc2TypeIi]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.iso27001Cryptography,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-3',
    slug: 'iso27001-a-8-24-cryptography',
    namespace: 'default',
    name: 'A.8.24 Use of Cryptography',
    description: 'Rules for effective use of cryptography, including key management.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'A.8.24',
      description: 'Rules for the effective use of cryptography are defined and implemented.',
      status: 'met',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.iso27001]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.iso27001SupplierSecurity,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-4',
    slug: 'iso27001-a-5-19-supplier-security',
    namespace: 'default',
    name: 'A.5.19 Supplier Relationships Security',
    description: 'Manages information security risks associated with supplier relationships.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['suppliers'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'A.5.19',
      description: 'Security requirements are agreed with suppliers and periodically reviewed.',
      status: 'in-progress',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.iso27001]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.pciProtectCardholderData,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-5',
    slug: 'pci-req-3-protect-cardholder-data',
    namespace: 'default',
    name: 'Req 3 - Protect Stored Cardholder Data',
    description: 'Stored cardholder data is rendered unreadable wherever it is stored.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'cryptography'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'PCI-3',
      description: 'Stored cardholder data is protected through tokenization or encryption.',
      status: 'met',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.pciDss]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.pciTrackMonitorAccess,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-6',
    slug: 'pci-req-10-track-monitor-access',
    namespace: 'default',
    name: 'Req 10 - Track and Monitor Access to Cardholder Data',
    description: 'All access to network resources and cardholder data is tracked and monitored.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'monitoring'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'PCI-10',
      description: 'Access to cardholder data systems is logged and reviewed regularly.',
      status: 'met',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.pciDss]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.gdprSecurityOfProcessing,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-7',
    slug: 'gdpr-art-32-security-of-processing',
    namespace: 'default',
    name: 'Art. 32 - Security of Processing',
    description: 'Appropriate technical and organisational measures protect personal data.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'GDPR-32',
      description:
        'Technical and organisational measures ensure a level of security appropriate to the risk.',
      status: 'in-progress',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.gdpr]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.complianceRequirements.gdprRightToErasure,
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-8',
    slug: 'gdpr-art-17-right-to-erasure',
    namespace: 'default',
    name: 'Art. 17 - Right to Erasure',
    description: 'Customers can request deletion of their personal data without undue delay.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.complianceRequirement,
    data: {
      requirement_code: 'GDPR-17',
      description: 'Data subject erasure requests are fulfilled within the required timeframe.',
      status: 'not-started',
      framework: [DEMO_RISK_COMPLIANCE_IDS.frameworks.gdpr]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoControlEntities: SeedEntityInput[] = [
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.mfaEnforcement,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-1',
    slug: 'mfa-enforcement',
    namespace: 'default',
    name: 'MFA Enforcement',
    description: 'Multi-factor authentication is required for all production system access.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control', 'preventive'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2026-01-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.siemAlerting,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-2',
    slug: 'siem-alerting',
    namespace: 'default',
    name: 'SIEM Alerting',
    description: 'Centralized log aggregation and alerting on anomalous system behavior.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring', 'detective'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'detective',
      design_effectiveness: 'effective',
      operating_effectiveness: 'partially-effective',
      last_verified: '2025-11-15'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.encryptionAtRest,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-3',
    slug: 'encryption-at-rest',
    namespace: 'default',
    name: 'Encryption at Rest',
    description: 'All production data stores use volume- and field-level encryption at rest.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography', 'preventive'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2025-12-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.vendorSecurityReview,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-4',
    slug: 'vendor-security-review',
    namespace: 'default',
    name: 'Vendor Security Review',
    description: 'Annual security questionnaire and evidence review for critical vendors.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['suppliers', 'detective'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'detective',
      design_effectiveness: 'effective',
      operating_effectiveness: 'partially-effective',
      last_verified: '2025-10-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.cardholderDataTokenization,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-5',
    slug: 'cardholder-data-tokenization',
    namespace: 'default',
    name: 'Cardholder Data Tokenization',
    description: 'Card numbers are tokenized at capture; no raw PAN is stored.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'preventive'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2025-12-15'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.paymentAccessLogging,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-6',
    slug: 'payment-access-logging',
    namespace: 'default',
    name: 'Payment Access Logging',
    description: 'All access to the payments platform and cardholder data is logged and reviewed.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'detective'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'detective',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2025-11-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.piiAccessControls,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-7',
    slug: 'pii-access-controls',
    namespace: 'default',
    name: 'PII Access Controls',
    description: 'Role-based access restricts customer PII to staff with a business need.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy', 'preventive'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2025-12-20'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.controls.dataDeletionAutomation,
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-8',
    slug: 'data-deletion-automation',
    namespace: 'default',
    name: 'Data Deletion Automation',
    description: 'Automated workflow purges customer PII across systems on erasure request.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy', 'corrective'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.control,
    data: {
      control_type: 'corrective',
      design_effectiveness: 'partially-effective',
      operating_effectiveness: 'not-tested',
      last_verified: '2025-09-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoRiskEntities: SeedEntityInput[] = [
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.customerAccountTakeover,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-1',
    slug: 'customer-account-takeover',
    namespace: 'default',
    name: 'Customer Account Takeover via Credential Stuffing',
    description: 'Reused or leaked credentials could be used to hijack customer accounts.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 3,
      impact: 4,
      mitigation_effectiveness: 'partial',
      risk_owner: 'Head of Security',
      status: 'open',
      treatment_target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.undetectedDataExfiltration,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-2',
    slug: 'undetected-data-exfiltration',
    namespace: 'default',
    name: 'Undetected Data Exfiltration',
    description: 'Anomalous outbound data transfer could go unnoticed without active monitoring.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 4,
      mitigation_effectiveness: 'substantial',
      risk_owner: 'Head of Security',
      status: 'mitigating',
      treatment_target_date: '2026-05-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.plaintextCustomerPiiAtRest,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-3',
    slug: 'plaintext-customer-pii-at-rest',
    namespace: 'default',
    name: 'Plaintext Customer PII at Rest',
    description:
      'Customer PII stored without encryption could be exposed by a storage-layer breach.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography', 'privacy'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 4,
      mitigation_effectiveness: 'full',
      risk_owner: 'Head of Security',
      status: 'accepted',
      treatment_target_date: '2026-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.thirdPartyVendorDataBreach,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-4',
    slug: 'third-party-vendor-data-breach',
    namespace: 'default',
    name: 'Third-Party Vendor Data Breach',
    description: 'A breach at a critical cloud vendor could expose customer or operational data.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['suppliers'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 3,
      mitigation_effectiveness: 'partial',
      risk_owner: 'Head of Security',
      status: 'open',
      treatment_target_date: '2026-08-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.paymentCardDataBreach,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-5',
    slug: 'payment-card-data-breach',
    namespace: 'default',
    name: 'Payment Card Data Breach',
    description: 'A compromise of the payments platform could expose stored cardholder data.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'cryptography'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 5,
      mitigation_effectiveness: 'substantial',
      risk_owner: 'Head of Payments Engineering',
      status: 'mitigating',
      treatment_target_date: '2026-04-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.unauthorizedAccessToPaymentLogs,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-6',
    slug: 'unauthorized-access-to-payment-transaction-logs',
    namespace: 'default',
    name: 'Unauthorized Access to Payment Transaction Logs',
    description: 'Insufficiently restricted log access could expose cardholder transaction detail.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['payments', 'monitoring'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 3,
      mitigation_effectiveness: 'substantial',
      risk_owner: 'Head of Payments Engineering',
      status: 'mitigating',
      treatment_target_date: '2026-05-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.unauthorizedInternalPiiAccess,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-7',
    slug: 'unauthorized-internal-pii-access',
    namespace: 'default',
    name: 'Unauthorized Internal Access to Customer PII',
    description: 'Overly broad internal access could let staff view PII without a business need.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy', 'access-control'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 2,
      impact: 3,
      mitigation_effectiveness: 'substantial',
      risk_owner: 'Head of Security',
      status: 'mitigating',
      treatment_target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RISK_COMPLIANCE_IDS.risks.nonCompliantErasureRequests,
    workspace: WORKSPACE_ID,
    public_id: 'RISK-8',
    slug: 'non-compliant-data-subject-erasure-requests',
    namespace: 'default',
    name: 'Non-Compliant Data Subject Erasure Requests',
    description: 'Manual, inconsistent erasure handling risks missing regulatory deadlines.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['privacy'],
    links: [],
    schema_id: SEED_SCHEMA_IDS.risk,
    data: {
      likelihood: 3,
      impact: 3,
      mitigation_effectiveness: 'partial',
      risk_owner: 'Head of Security',
      status: 'open',
      treatment_target_date: '2026-07-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const demoRetentionPolicyEntities: SeedEntityInput[] = [
  {
    id: DEMO_RETENTION_IDS.policies.paymentTransactionRecords,
    workspace: WORKSPACE_ID,
    public_id: 'RETN-1',
    slug: 'payment-transaction-records',
    namespace: 'default',
    name: 'Payment Transaction Records',
    description: 'Retention for payment transaction and settlement records.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['governance', 'retention', 'payments'],
    links: [],
    schema_id: RETENTION_IDS.policySchema,
    data: { duration: 7, time_unit: 'years' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RETENTION_IDS.policies.customerPiiRecords,
    workspace: WORKSPACE_ID,
    public_id: 'RETN-2',
    slug: 'customer-pii-records',
    namespace: 'default',
    name: 'Customer PII Records',
    description: 'Retention for customer personal data after account closure.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['governance', 'retention', 'privacy'],
    links: [],
    schema_id: RETENTION_IDS.policySchema,
    data: { duration: 3, time_unit: 'years' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RETENTION_IDS.policies.marketingConsentRecords,
    workspace: WORKSPACE_ID,
    public_id: 'RETN-3',
    slug: 'marketing-consent-records',
    namespace: 'default',
    name: 'Marketing Consent Records',
    description: 'Retention for customer marketing consent and preference records.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['governance', 'retention', 'marketing'],
    links: [],
    schema_id: RETENTION_IDS.policySchema,
    data: { duration: 2, time_unit: 'years' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: DEMO_RETENTION_IDS.policies.orderFulfillmentRecords,
    workspace: WORKSPACE_ID,
    public_id: 'RETN-4',
    slug: 'order-and-fulfillment-records',
    namespace: 'default',
    name: 'Order & Fulfillment Records',
    description: 'Retention for order, shipment, and fulfillment records.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['governance', 'retention', 'fulfillment'],
    links: [],
    schema_id: RETENTION_IDS.policySchema,
    data: { duration: 5, time_unit: 'years' },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];
