import type { Entity } from '../../domain/catalog/db/catalogDatabase';
import { computeEntityCompleteness } from '../../utils/completeness';
import { materializeDerivedFields } from '../../domain/derived/derivedFields';
import { seededProjects } from '../seedFixtures';
import { seedSchemas } from './catalog';
import {
  GLOSSARY_IDS,
  LIFECYCLE2_IDS,
  LIFECYCLE_IDS,
  STRATEGY_IDS,
  TEAM2_IDS,
  TEAM_IDS,
  TECHNOLOGY_IDS,
  TECHNOLOGY_RELEASE_IDS,
  WORKSPACE2_ID,
  WORKSPACE_ID,
  now
} from './constants';

type SeedEntityInput = Omit<Entity, 'completeness'>;

const seedTechnologies: SeedEntityInput[] = [
  {
    id: TECHNOLOGY_IDS.nodejs,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-1',
    slug: 'nodejs',
    namespace: 'default',
    name: 'Node.js',
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine.",
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://nodejs.org', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Node.js',
      provider_product: 'nodejs',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.react,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-2',
    slug: 'react',
    namespace: 'default',
    name: 'React',
    description: 'A JavaScript library for building user interfaces.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['framework', 'frontend'],
    links: [{ url: 'https://react.dev', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'React',
      provider_product: 'react',
      category: 'framework',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.go,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-3',
    slug: 'go',
    namespace: 'default',
    name: 'Go',
    description:
      'An open source programming language that makes it easy to build simple, reliable, and efficient software.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://go.dev', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Go',
      provider_product: 'go',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.python,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-4',
    slug: 'python',
    namespace: 'default',
    name: 'Python',
    description:
      'A programming language that lets you work quickly and integrate systems more effectively.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'data'],
    links: [{ url: 'https://www.python.org', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Python',
      provider_product: 'python',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.java,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-5',
    slug: 'java',
    namespace: 'default',
    name: 'Java',
    description: 'A high-level, class-based, object-oriented programming language.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://www.java.com', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Java',
      provider_product: 'java',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.rust,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-6',
    slug: 'rust',
    namespace: 'default',
    name: 'Rust',
    description: 'A language empowering everyone to build reliable and efficient software.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-30',
    tags: ['language', 'backend'],
    links: [{ url: 'https://www.rust-lang.org', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Rust',
      provider_product: 'rust',
      category: 'language',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.postgresql,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-7',
    slug: 'postgresql',
    namespace: 'default',
    name: 'PostgreSQL',
    description: "The world's most advanced open source relational database.",
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'managed'],
    links: [{ url: 'https://www.postgresql.org', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'PostgreSQL',
      provider_product: 'postgresql',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.redis,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-8',
    slug: 'redis',
    namespace: 'default',
    name: 'Redis',
    description: 'An open source, in-memory data structure store.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'cache'],
    links: [{ url: 'https://redis.io', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Redis',
      provider_product: 'redis',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.kafka,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-9',
    slug: 'kafka',
    namespace: 'default',
    name: 'Apache Kafka',
    description: 'An open-source distributed event streaming platform.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['messaging', 'managed'],
    links: [{ url: 'https://kafka.apache.org', title: 'Official site', type: 'website' }],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Apache Kafka',
      provider_product: 'apache-kafka',
      category: 'runtime',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_IDS.elasticsearch,
    workspace: WORKSPACE_ID,
    public_id: 'TECH-10',
    slug: 'elasticsearch',
    namespace: 'default',
    name: 'Elasticsearch',
    description: 'A distributed, RESTful search and analytics engine.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'search'],
    links: [
      { url: 'https://www.elastic.co/elasticsearch', title: 'Official site', type: 'website' }
    ],
    schema_id: '00000000-0000-0000-0000-000000000007',
    data: {
      product: 'Elasticsearch',
      provider_product: 'elasticsearch',
      category: 'database',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

const seedTechnologyReleases: SeedEntityInput[] = [
  {
    id: TECHNOLOGY_RELEASE_IDS.nodejs20,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-1',
    slug: 'nodejs-20',
    namespace: 'default',
    name: 'Node.js 20',
    description: 'Node.js 20 release cycle tracked for runtime support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['runtime', 'javascript'],
    links: [{ url: 'https://endoflife.date/nodejs', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.nodejs],
      provider_product: 'nodejs',
      release_cycle: '20',
      latest_version: '20.19.0',
      release_date: '2023-04-18',
      active_support_until: '2024-10-22',
      security_support_until: '2026-04-30',
      eol_date: '2026-04-30',
      source_url: 'https://endoflife.date/nodejs',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.react18,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-2',
    slug: 'react-18',
    namespace: 'default',
    name: 'React 18',
    description: 'React 18 release cycle tracked for frontend support planning.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['framework', 'frontend'],
    links: [{ url: 'https://endoflife.date/react', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.react],
      provider_product: 'react',
      release_cycle: '18',
      latest_version: '18.3.1',
      release_date: '2022-06-14',
      active_support_until: '2025-12-31',
      security_support_until: '2025-12-31',
      eol_date: '2025-12-31',
      source_url: 'https://endoflife.date/react',
      last_synchronized: '2026-01-01',
      category: 'framework',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.go122,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-3',
    slug: 'go-1-22',
    namespace: 'default',
    name: 'Go 1.22',
    description: 'Go 1.22 release cycle tracked for service support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://endoflife.date/go', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.go],
      provider_product: 'go',
      release_cycle: '1.22',
      latest_version: '1.22.12',
      release_date: '2024-02-06',
      active_support_until: '2025-02-01',
      security_support_until: '2025-02-01',
      eol_date: '2025-02-01',
      source_url: 'https://endoflife.date/go',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.python312,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-4',
    slug: 'python-3-12',
    namespace: 'default',
    name: 'Python 3.12',
    description: 'Python 3.12 release cycle tracked for service support planning.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'data'],
    links: [{ url: 'https://endoflife.date/python', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.python],
      provider_product: 'python',
      release_cycle: '3.12',
      latest_version: '3.12.9',
      release_date: '2023-10-02',
      active_support_until: '2024-10-07',
      security_support_until: '2028-10-31',
      eol_date: '2028-10-31',
      source_url: 'https://endoflife.date/python',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.java21,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-5',
    slug: 'java-21',
    namespace: 'default',
    name: 'Java 21',
    description: 'Java 21 release cycle tracked for service support planning.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['language', 'backend'],
    links: [{ url: 'https://endoflife.date/java', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.java],
      provider_product: 'java',
      release_cycle: '21',
      latest_version: '21.0.5',
      release_date: '2023-09-19',
      active_support_until: '2028-09-30',
      security_support_until: '2031-09-30',
      eol_date: '2031-09-30',
      source_url: 'https://endoflife.date/java',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.rust182,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-6',
    slug: 'rust-1-82',
    namespace: 'default',
    name: 'Rust 1.82',
    description: 'Rust 1.82 release cycle tracked for service support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-30',
    tags: ['language', 'backend'],
    links: [{ url: 'https://endoflife.date/rust', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.rust],
      provider_product: 'rust',
      release_cycle: '1.82',
      latest_version: '1.82.0',
      release_date: '2024-10-17',
      active_support_until: '2025-04-17',
      security_support_until: '2025-04-17',
      eol_date: '2025-04-17',
      source_url: 'https://endoflife.date/rust',
      last_synchronized: '2026-01-01',
      category: 'language',
      radar_status: 'trial'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.postgres15,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-7',
    slug: 'postgresql-15',
    namespace: 'default',
    name: 'PostgreSQL 15',
    description: 'PostgreSQL 15 release cycle tracked for database support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'managed'],
    links: [
      { url: 'https://endoflife.date/postgresql', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.postgresql],
      provider_product: 'postgresql',
      release_cycle: '15',
      latest_version: '15.10',
      release_date: '2022-10-13',
      active_support_until: '2026-11-11',
      security_support_until: '2027-11-11',
      eol_date: '2027-11-11',
      source_url: 'https://endoflife.date/postgresql',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.redis7,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-8',
    slug: 'redis-7',
    namespace: 'default',
    name: 'Redis 7',
    description: 'Redis 7 release cycle tracked for cache support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'cache'],
    links: [{ url: 'https://endoflife.date/redis', title: 'Lifecycle source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.redis],
      provider_product: 'redis',
      release_cycle: '7',
      latest_version: '7.2.6',
      release_date: '2022-04-27',
      active_support_until: '2026-04-30',
      security_support_until: '2027-04-30',
      eol_date: '2027-04-30',
      source_url: 'https://endoflife.date/redis',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'adopt'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.kafka37,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-9',
    slug: 'kafka-3-7',
    namespace: 'default',
    name: 'Kafka 3.7',
    description: 'Kafka 3.7 release cycle tracked for messaging support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['messaging', 'managed'],
    links: [
      { url: 'https://endoflife.date/apache-kafka', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.kafka],
      provider_product: 'apache-kafka',
      release_cycle: '3.7',
      latest_version: '3.7.2',
      release_date: '2024-02-28',
      active_support_until: '2025-02-28',
      security_support_until: '2025-02-28',
      eol_date: '2025-02-28',
      source_url: 'https://endoflife.date/apache-kafka',
      last_synchronized: '2026-01-01',
      category: 'runtime',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: TECHNOLOGY_RELEASE_IDS.elasticsearch8,
    workspace: WORKSPACE_ID,
    public_id: 'TEC-10',
    slug: 'elasticsearch-8',
    namespace: 'default',
    name: 'Elasticsearch 8',
    description: 'Elasticsearch 8 release cycle tracked for search support planning.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['database', 'search'],
    links: [
      { url: 'https://endoflife.date/elasticsearch', title: 'Lifecycle source', type: 'source' }
    ],
    schema_id: '00000000-0000-0000-0000-000000000006',
    data: {
      technology: [TECHNOLOGY_IDS.elasticsearch],
      provider_product: 'elasticsearch',
      release_cycle: '8',
      latest_version: '8.15.3',
      release_date: '2022-08-23',
      active_support_until: '2026-08-31',
      security_support_until: '2027-08-31',
      eol_date: '2027-08-31',
      source_url: 'https://endoflife.date/elasticsearch',
      last_synchronized: '2026-01-01',
      category: 'database',
      radar_status: 'assess'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

const seedRiskComplianceEntities: SeedEntityInput[] = [
  {
    id: '00000000-0000-0000-0017-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-1',
    slug: 'soc-2-type-ii',
    namespace: 'default',
    name: 'SOC 2 Type II',
    description: 'Trust Services Criteria for security, availability, and confidentiality.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'audit'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000015',
    data: { framework_kind: 'soc2', description: 'Annual SOC 2 Type II audit cycle.' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0017-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'FRWK-2',
    slug: 'iso-27001',
    namespace: 'default',
    name: 'ISO 27001',
    description: 'International standard for information security management systems.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['compliance', 'audit'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000015',
    data: { framework_kind: 'iso27001', description: 'ISMS certification, renewed annually.' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000f-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-1',
    slug: 'soc2-cc6-1-logical-access',
    namespace: 'default',
    name: 'CC6.1 Logical Access Controls',
    description: 'Restricts logical access to authorized users and processes.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000016',
    data: {
      requirement_code: 'CC6.1',
      description: 'The entity implements logical access security measures.',
      status: 'met',
      framework: ['00000000-0000-0000-0017-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000f-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-2',
    slug: 'soc2-cc7-2-monitoring',
    namespace: 'default',
    name: 'CC7.2 System Monitoring',
    description: 'Monitors system components for anomalies indicative of security events.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000016',
    data: {
      requirement_code: 'CC7.2',
      description: 'The entity monitors system components for anomalous behavior.',
      status: 'in-progress',
      framework: ['00000000-0000-0000-0017-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000f-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'CREQ-3',
    slug: 'iso27001-a-8-24-cryptography',
    namespace: 'default',
    name: 'A.8.24 Use of Cryptography',
    description: 'Rules for effective use of cryptography, including key management.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000016',
    data: {
      requirement_code: 'A.8.24',
      description: 'The entity defines and implements rules for cryptography.',
      status: 'not-started',
      framework: ['00000000-0000-0000-0017-000000000002']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000d-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-1',
    slug: 'mfa-enforcement',
    namespace: 'default',
    name: 'MFA Enforcement',
    description: 'Multi-factor authentication is required for all production system access.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control', 'preventive'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000014',
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'effective',
      last_verified: '2026-01-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000d-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-2',
    slug: 'siem-alerting',
    namespace: 'default',
    name: 'SIEM Alerting',
    description: 'Centralized log aggregation and alerting on anomalous system behavior.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring', 'detective'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000014',
    data: {
      control_type: 'detective',
      design_effectiveness: 'effective',
      operating_effectiveness: 'partially-effective',
      last_verified: '2025-11-15'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000d-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'CTRL-3',
    slug: 'encryption-at-rest',
    namespace: 'default',
    name: 'Encryption at Rest',
    description: 'All production data stores use volume- and field-level encryption at rest.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography', 'preventive'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000014',
    data: {
      control_type: 'preventive',
      design_effectiveness: 'effective',
      operating_effectiveness: 'not-tested',
      last_verified: '2025-09-01'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000c-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'RISK-1',
    slug: 'unauthorized-production-access',
    namespace: 'default',
    name: 'Unauthorized Production Access',
    description: 'A compromised credential could be used to access production systems directly.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['access-control'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000013',
    data: {
      likelihood: 3,
      impact: 5,
      mitigation_effectiveness: 'substantial',
      risk_owner: 'Head of Security',
      status: 'mitigating',
      treatment_target_date: '2026-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000c-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'RISK-2',
    slug: 'undetected-data-exfiltration',
    namespace: 'default',
    name: 'Undetected Data Exfiltration',
    description: 'Anomalous outbound data transfer could go unnoticed without active monitoring.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['monitoring'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000013',
    data: {
      likelihood: 2,
      impact: 4,
      mitigation_effectiveness: 'partial',
      risk_owner: 'Head of Security',
      status: 'open',
      treatment_target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000c-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'RISK-3',
    slug: 'plaintext-data-at-rest',
    namespace: 'default',
    name: 'Plaintext Data at Rest',
    description: 'A misconfigured data store could expose sensitive data if not encrypted.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cryptography'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000013',
    data: {
      likelihood: 1,
      impact: 5,
      mitigation_effectiveness: 'full',
      risk_owner: 'Head of Security',
      status: 'accepted',
      treatment_target_date: '2026-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

// Strategy model examples (see #3020): nested Business Capabilities, Objective, Outcome,
// Initiative, and Measure linked with reference fields and typed relations.
const seedStrategyEntities: SeedEntityInput[] = [
  {
    id: STRATEGY_IDS.businessCapabilities.customerEngagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-1',
    slug: 'customer-engagement',
    namespace: 'default',
    name: 'Customer Engagement',
    description: 'The ability to attract, serve, and retain customers across their journey.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'engagement'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Coordinate customer-facing capabilities that support retention and growth.',
      target_date: '2027-06-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.businessCapabilities.selfServiceManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-2',
    slug: 'self-service-management',
    namespace: 'default',
    name: 'Self-Service Management',
    description: 'The ability to provide customers with effective self-service journeys.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'self-service'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Enable customers to resolve common needs without assisted support.',
      parent: [STRATEGY_IDS.businessCapabilities.customerEngagement],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.businessCapabilities.accountManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-3',
    slug: 'account-management',
    namespace: 'default',
    name: 'Account Management',
    description: 'The ability to let customers manage their accounts and subscriptions.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'accounts'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Support secure profile, subscription, and entitlement management.',
      parent: [STRATEGY_IDS.businessCapabilities.selfServiceManagement],
      target_date: '2027-03-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.businessCapabilities.platformReliability,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-4',
    slug: 'platform-reliability',
    namespace: 'default',
    name: 'Platform Reliability',
    description: 'The ability to operate resilient and dependable digital platforms.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'reliability'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Maintain dependable platform services through resilient operations.',
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.businessCapabilities.observabilityManagement,
    workspace: WORKSPACE_ID,
    public_id: 'CAP-5',
    slug: 'observability-management',
    namespace: 'default',
    name: 'Observability Management',
    description: 'The ability to monitor platform health and respond to operational signals.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['platform', 'observability'],
    links: [],
    schema_id: STRATEGY_IDS.businessCapabilitySchema,
    data: {
      description: 'Provide monitoring, alerting, and tracing for critical platform services.',
      parent: [STRATEGY_IDS.businessCapabilities.platformReliability],
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.objectives.improveCustomerRetention,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-1',
    slug: 'improve-customer-retention',
    namespace: 'default',
    name: 'Improve Customer Retention',
    description:
      'Reduce customer churn by making the self-service portal faster and more reliable.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'retention'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Improve retention by addressing the top causes of customer churn.',
      status: 'active',
      target_date: '2026-12-31'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.objectives.strengthenPlatformReliability,
    workspace: WORKSPACE_ID,
    public_id: 'OBJ-2',
    slug: 'strengthen-platform-reliability',
    namespace: 'default',
    name: 'Strengthen Platform Reliability',
    description: 'Raise platform uptime and reduce incident response time across core systems.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['reliability', 'platform'],
    links: [],
    schema_id: STRATEGY_IDS.objectiveSchema,
    data: {
      description: 'Reduce unplanned downtime through better observability and incident response.',
      status: 'active',
      target_date: '2026-09-30'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.outcomes.reduceChurnRate,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-1',
    slug: 'reduce-monthly-churn-rate',
    namespace: 'default',
    name: 'Reduce Monthly Churn Rate',
    description: 'Monthly customer churn trends downward quarter over quarter.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'retention'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Monthly churn rate declines as portal reliability and usability improve.',
      objectives: [STRATEGY_IDS.objectives.improveCustomerRetention]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.outcomes.increasePlatformUptime,
    workspace: WORKSPACE_ID,
    public_id: 'OUTC-2',
    slug: 'increase-platform-uptime',
    namespace: 'default',
    name: 'Increase Platform Uptime',
    description: 'Core systems consistently meet their uptime targets.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['reliability', 'platform'],
    links: [],
    schema_id: STRATEGY_IDS.outcomeSchema,
    data: {
      description: 'Uptime across core systems improves as observability gaps are closed.',
      objectives: [STRATEGY_IDS.objectives.strengthenPlatformReliability]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.initiatives.portalRedesign,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-1',
    slug: 'customer-portal-redesign',
    namespace: 'default',
    name: 'Customer Portal Redesign',
    description: 'Rebuild the customer portal frontend for speed and accessibility.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'portal'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'A ground-up rebuild of the customer portal frontend.',
      status: 'active',
      objectives: [STRATEGY_IDS.objectives.improveCustomerRetention],
      outcomes: [STRATEGY_IDS.outcomes.reduceChurnRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.initiatives.observabilityUplift,
    workspace: WORKSPACE_ID,
    public_id: 'INIT-2',
    slug: 'observability-uplift',
    namespace: 'default',
    name: 'Observability Uplift',
    description: 'Extend monitoring, alerting, and tracing coverage across core systems.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['reliability', 'observability'],
    links: [],
    schema_id: STRATEGY_IDS.initiativeSchema,
    data: {
      description: 'Close monitoring gaps identified during recent incident reviews.',
      status: 'active',
      objectives: [STRATEGY_IDS.objectives.strengthenPlatformReliability],
      outcomes: [STRATEGY_IDS.outcomes.increasePlatformUptime]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.measures.monthlyChurnRate,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-1',
    slug: 'monthly-churn-rate',
    namespace: 'default',
    name: 'Monthly Churn Rate',
    description: 'Percentage of customers lost per month.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['customer', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked monthly from billing and account cancellation data.',
      unit: '%',
      target_value: 3,
      outcomes: [STRATEGY_IDS.outcomes.reduceChurnRate]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: STRATEGY_IDS.measures.platformUptimePercent,
    workspace: WORKSPACE_ID,
    public_id: 'MEAS-2',
    slug: 'platform-uptime-percent',
    namespace: 'default',
    name: 'Platform Uptime %',
    description: 'Rolling 30-day uptime across core production systems.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['reliability', 'kpi'],
    links: [],
    schema_id: STRATEGY_IDS.measureSchema,
    data: {
      description: 'Tracked from uptime monitoring across production systems.',
      unit: '%',
      target_value: 99.9,
      outcomes: [STRATEGY_IDS.outcomes.increasePlatformUptime]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

export const seedEntitiesRaw: SeedEntityInput[] = [
  ...seedTechnologies,
  ...seedTechnologyReleases,
  ...seedRiskComplianceEntities,
  ...seedStrategyEntities,
  {
    id: '00000000-0000-0000-0001-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'DOM-1',
    slug: 'engineering',
    namespace: 'default',
    name: 'Engineering',
    description:
      'The core engineering domain covering all customer-facing products and infrastructure.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'customer-facing'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000001',
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0002-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-1',
    slug: 'customer-portal',
    namespace: 'default',
    name: 'Customer Portal',
    description: 'Public-facing portal for customer self-service.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle_date: '2026-12-31',
    tags: ['tier-0', 'customer-facing'],
    links: [{ url: 'https://wiki.example.com/customer-portal', title: 'Wiki', type: 'docs' }],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000001'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0002-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-2',
    slug: 'identity-platform',
    namespace: 'default',
    name: 'Identity Platform',
    description: 'Centralised authentication and authorisation service.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-0', 'security'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000001'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000b-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'VND-1',
    slug: 'acme-cloud',
    namespace: 'default',
    name: 'Acme Cloud',
    description: 'Cloud services vendor providing the Customer Portal license.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['vendor'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000010',
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000b-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'VND-2',
    slug: 'nordic-systems',
    namespace: 'default',
    name: 'Nordic Systems',
    description: 'Systems vendor providing managed support for the Identity Platform.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['vendor'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000010',
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000a-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'CON-1',
    slug: 'acme-cloud-customer-portal-license',
    namespace: 'default',
    name: 'Acme Cloud Customer Portal License',
    description: 'Annual software license for the Customer Portal platform.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['vendor', 'license'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000009',
    data: {
      vendor: ['00000000-0000-0000-000b-000000000001'],
      contract_start: '2026-01-01',
      contract_end: '2026-12-31',
      annual_cost: { amount: 125000, currency: 'USD' },
      setup_fee: { amount: 15000, currency: 'USD' }
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000a-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'CON-2',
    slug: 'nordic-support-identity-platform',
    namespace: 'default',
    name: 'Nordic Support Identity Platform',
    description: 'Managed support agreement for the Identity Platform.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['vendor', 'support'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000009',
    data: {
      vendor: ['00000000-0000-0000-000b-000000000002'],
      contract_start: '2026-02-01',
      contract_end: '2027-01-31',
      annual_cost: { amount: 84000, currency: 'EUR' },
      setup_fee: { amount: 0, currency: 'EUR' }
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-000a-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'CON-3',
    slug: 'acme-cloud-customer-portal-support',
    namespace: 'default',
    name: 'Acme Cloud Customer Portal Support',
    description: 'Support agreement for the Customer Portal platform.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['vendor', 'support'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000009',
    data: {
      vendor: ['00000000-0000-0000-000b-000000000001'],
      contract_start: '2026-03-01',
      contract_end: '2027-02-28',
      annual_cost: { amount: 30000, currency: 'USD' },
      setup_fee: { amount: 0, currency: 'USD' }
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0008-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'DE-1',
    slug: 'customer-credentials',
    namespace: 'default',
    name: 'Customer Credentials',
    description: 'Username/password or session token used to authenticate a customer.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000008',
    data: { classification: 'sensitive' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0008-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'DE-2',
    slug: 'transaction-events',
    namespace: 'default',
    name: 'Transaction Events',
    description: 'Payment transaction events used for financial reporting.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000008',
    data: { classification: 'non-sensitive' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0008-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'DE-3',
    slug: 'clickstream-events',
    namespace: 'default',
    name: 'Clickstream Events',
    description: 'User behaviour and clickstream events captured for product analytics.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: [],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000008',
    data: { classification: 'sensitive' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0004-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'API-1',
    slug: 'customer-api',
    namespace: 'default',
    name: 'Customer API',
    description: 'REST API exposing customer data to the portal frontend.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'public'],
    links: [{ url: 'https://api.example.com/docs/customer', title: 'API Docs', type: 'docs' }],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'openapi',
      protocols: ['https-rest'],
      system: ['00000000-0000-0000-0002-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0004-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'API-2',
    slug: 'auth-api',
    namespace: 'default',
    name: 'Auth API',
    description: 'gRPC API for token issuance and validation.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['grpc', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'grpc',
      protocols: ['grpc'],
      system: ['00000000-0000-0000-0002-000000000002']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-1',
    slug: 'api-gateway',
    namespace: 'default',
    name: 'API Gateway',
    description: 'Edge gateway that routes requests and enforces rate limits.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['nodejs', 'tier-0'],
    links: [{ url: 'https://github.com/example/api-gateway', title: 'Source', type: 'source' }],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.nodejs20],
      system: ['00000000-0000-0000-0002-000000000001'],
      provides_apis: ['00000000-0000-0000-0004-000000000001'],
      consumes_apis: ['00000000-0000-0000-0004-000000000002'],
      depends_on: ['00000000-0000-0000-0003-000000000003']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-2',
    slug: 'frontend-app',
    namespace: 'default',
    name: 'Frontend App',
    description: 'React single-page application served to end users.',
    owner: TEAM_IDS.design,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: LIFECYCLE_IDS.deprecated,
    target_lifecycle_date: '2026-12-31',
    tags: ['react', 'frontend'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.react18],
      system: ['00000000-0000-0000-0002-000000000001'],
      consumes_apis: [
        '00000000-0000-0000-0004-000000000001',
        '00000000-0000-0000-0004-000000000002'
      ],
      depends_on: ['00000000-0000-0000-0003-000000000001', '00000000-0000-0000-0003-000000000003']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-3',
    slug: 'auth-service',
    namespace: 'default',
    name: 'Auth Service',
    description: 'Issues and validates JWTs; integrates with the identity platform.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-09-30',
    tags: ['go', 'security'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.go122],
      system: ['00000000-0000-0000-0002-000000000002'],
      provides_apis: ['00000000-0000-0000-0004-000000000002']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000001',
    workspace: WORKSPACE_ID,
    public_id: 'RES-1',
    slug: 'postgres-main',
    namespace: 'default',
    name: 'Postgres Main',
    description: 'Primary PostgreSQL cluster used by the Customer Portal system.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['postgres', 'managed'],
    links: [
      { url: 'https://grafana.example.com/d/postgres-main', title: 'Dashboard', type: 'dashboard' }
    ],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'database',
      technology_releases: [TECHNOLOGY_RELEASE_IDS.postgres15],
      system: ['00000000-0000-0000-0002-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Payments domain
  {
    id: '00000000-0000-0000-0001-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'DOM-2',
    slug: 'payments',
    namespace: 'default',
    name: 'Payments',
    description: 'Payment processing, billing and ledger systems for the checkout experience.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'revenue'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000001',
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0001-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'DOM-3',
    slug: 'data-and-analytics',
    namespace: 'default',
    name: 'Data & Analytics',
    description: 'Ingestion, warehousing and reporting for company-wide analytics.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['core', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000001',
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Additional systems
  {
    id: '00000000-0000-0000-0002-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-3',
    slug: 'payments-platform',
    namespace: 'default',
    name: 'Payments Platform',
    description: 'Handles payment authorization, capture, refunds and ledger reconciliation.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-0', 'revenue'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000002'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0002-000000000004',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-4',
    slug: 'analytics-platform',
    namespace: 'default',
    name: 'Analytics Platform',
    description: 'Ingests events from product systems and powers internal reporting.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-1', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000003'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0002-000000000005',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-5',
    slug: 'notification-hub',
    namespace: 'default',
    name: 'Notification Hub',
    description: 'Centralised outbound messaging: push, email and webhooks.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['tier-1', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000001'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0002-000000000006',
    workspace: WORKSPACE_ID,
    public_id: 'SYS-6',
    slug: 'search-platform',
    namespace: 'default',
    name: 'Search Platform',
    description: 'Full-text search and recommendations across the product catalog.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-01',
    tags: ['tier-1', 'search'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000002',
    data: { domain: ['00000000-0000-0000-0001-000000000001'] },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Additional APIs
  {
    id: '00000000-0000-0000-0004-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'API-3',
    slug: 'payments-api',
    namespace: 'default',
    name: 'Payments API',
    description: 'REST API for authorizing and capturing payments.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'openapi',
      protocols: ['https-rest'],
      system: ['00000000-0000-0000-0002-000000000003']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0004-000000000004',
    workspace: WORKSPACE_ID,
    public_id: 'API-4',
    slug: 'analytics-api',
    namespace: 'default',
    name: 'Analytics API',
    description: 'GraphQL API exposing aggregated analytics data to internal dashboards.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['graphql', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'graphql',
      protocols: ['https-rest'],
      system: ['00000000-0000-0000-0002-000000000004']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0004-000000000005',
    workspace: WORKSPACE_ID,
    public_id: 'API-5',
    slug: 'notifications-api',
    namespace: 'default',
    name: 'Notifications API',
    description: 'AsyncAPI event contract for push, email and webhook delivery.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['asyncapi', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'asyncapi',
      protocols: ['kafka', 'https-rest'],
      system: ['00000000-0000-0000-0002-000000000005']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0004-000000000006',
    workspace: WORKSPACE_ID,
    public_id: 'API-6',
    slug: 'search-api',
    namespace: 'default',
    name: 'Search API',
    description: 'REST API for full-text search and typeahead suggestions.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rest', 'search'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000004',
    data: {
      api_type: 'openapi',
      protocols: ['https-rest'],
      system: ['00000000-0000-0000-0002-000000000006']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Additional components
  {
    id: '00000000-0000-0000-0003-000000000004',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-4',
    slug: 'payment-service',
    namespace: 'default',
    name: 'Payment Service',
    description: 'Orchestrates payment authorization and capture against external providers.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'revenue'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.go122],
      system: ['00000000-0000-0000-0002-000000000003'],
      provides_apis: ['00000000-0000-0000-0004-000000000003'],
      consumes_apis: ['00000000-0000-0000-0004-000000000002'],
      depends_on: ['00000000-0000-0000-0003-000000000005']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000005',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-5',
    slug: 'ledger-service',
    namespace: 'default',
    name: 'Ledger Service',
    description: 'Double-entry ledger recording all payment and refund transactions.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['java', 'revenue'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.java21],
      system: ['00000000-0000-0000-0002-000000000003']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000006',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-6',
    slug: 'fraud-detection-service',
    namespace: 'default',
    name: 'Fraud Detection Service',
    description: 'Scores transactions for fraud risk before payment capture.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-07-01',
    tags: ['python', 'security'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.python312],
      system: ['00000000-0000-0000-0002-000000000003'],
      consumes_apis: ['00000000-0000-0000-0004-000000000003'],
      depends_on: ['00000000-0000-0000-0003-000000000005']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000007',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-7',
    slug: 'analytics-ingestion-worker',
    namespace: 'default',
    name: 'Analytics Ingestion Worker',
    description: 'Consumes product and payment events and lands them in the data warehouse.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.python312],
      system: ['00000000-0000-0000-0002-000000000004'],
      consumes_apis: [
        '00000000-0000-0000-0004-000000000001',
        '00000000-0000-0000-0004-000000000003'
      ]
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000008',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-8',
    slug: 'reporting-dashboard',
    namespace: 'default',
    name: 'Reporting Dashboard',
    description: 'Internal dashboard surfacing revenue and product analytics.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['react', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.react18],
      system: ['00000000-0000-0000-0002-000000000004'],
      consumes_apis: ['00000000-0000-0000-0004-000000000004'],
      depends_on: ['00000000-0000-0000-0003-000000000007']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000009',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-9',
    slug: 'notification-dispatcher',
    namespace: 'default',
    name: 'Notification Dispatcher',
    description: 'Fans out outbound notification events to channel-specific senders.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['nodejs', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.nodejs20],
      system: ['00000000-0000-0000-0002-000000000005'],
      provides_apis: ['00000000-0000-0000-0004-000000000005']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000a',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-10',
    slug: 'webhook-relay',
    namespace: 'default',
    name: 'Webhook Relay',
    description: 'Delivers outbound webhooks with retries and signature verification.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.go122],
      system: ['00000000-0000-0000-0002-000000000005'],
      consumes_apis: ['00000000-0000-0000-0004-000000000005'],
      depends_on: ['00000000-0000-0000-0003-000000000009']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000b',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-11',
    slug: 'search-service',
    namespace: 'default',
    name: 'Search Service',
    description: 'Serves full-text search queries backed by the Elasticsearch cluster.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-06-01',
    tags: ['rust', 'search'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.rust182],
      system: ['00000000-0000-0000-0002-000000000006'],
      provides_apis: ['00000000-0000-0000-0004-000000000006']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000c',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-12',
    slug: 'recommendation-engine',
    namespace: 'default',
    name: 'Recommendation Engine',
    description: 'Generates personalised recommendations from search and behavioural signals.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.proposed,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'search'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.python312],
      system: ['00000000-0000-0000-0002-000000000006'],
      consumes_apis: ['00000000-0000-0000-0004-000000000006'],
      depends_on: ['00000000-0000-0000-0003-00000000000b']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000d',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-13',
    slug: 'email-service',
    namespace: 'default',
    name: 'Email Service',
    description: 'Renders and sends transactional email via the notification hub.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['nodejs', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.nodejs20],
      system: ['00000000-0000-0000-0002-000000000005'],
      consumes_apis: ['00000000-0000-0000-0004-000000000005'],
      depends_on: ['00000000-0000-0000-0003-000000000009']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000e',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-14',
    slug: 'feature-flag-service',
    namespace: 'default',
    name: 'Feature Flag Service',
    description: 'Serves feature flag evaluations to the portal frontend and gateway.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'tier-1'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.go122],
      system: ['00000000-0000-0000-0002-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-00000000000f',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-15',
    slug: 'rate-limiter',
    namespace: 'default',
    name: 'Rate Limiter',
    description: 'Sidecar enforcing per-client rate limits at the edge.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rust', 'tier-1'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.rust182],
      system: ['00000000-0000-0000-0002-000000000001'],
      depends_on: ['00000000-0000-0000-0003-00000000000e']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0003-000000000010',
    workspace: WORKSPACE_ID,
    public_id: 'CMP-16',
    slug: 'auth-migration-adapter',
    namespace: 'default',
    name: 'Auth Migration Adapter',
    description: 'Project-specific adapter used while migrating from legacy authentication.',
    owner: TEAM_IDS.security,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle_date: '2026-09-30',
    tags: ['go', 'security', 'migration'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000003',
    data: {
      technology_releases: [TECHNOLOGY_RELEASE_IDS.go122],
      system: ['00000000-0000-0000-0002-000000000002']
    },
    project_id: seededProjects.authMigration.id,
    created_at: now,
    updated_at: now
  },
  // Additional resources
  {
    id: '00000000-0000-0000-0005-000000000002',
    workspace: WORKSPACE_ID,
    public_id: 'RES-2',
    slug: 'redis-cache',
    namespace: 'default',
    name: 'Redis Cache',
    description: 'Session and response cache for the customer portal.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['redis', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'cache',
      technology_releases: [TECHNOLOGY_RELEASE_IDS.redis7],
      system: ['00000000-0000-0000-0002-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000003',
    workspace: WORKSPACE_ID,
    public_id: 'RES-3',
    slug: 'kafka-event-bus',
    namespace: 'default',
    name: 'Kafka Event Bus',
    description: 'Event backbone for notification and analytics event streams.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['kafka', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'message-queue',
      technology_releases: [TECHNOLOGY_RELEASE_IDS.kafka37],
      system: ['00000000-0000-0000-0002-000000000005']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000004',
    workspace: WORKSPACE_ID,
    public_id: 'RES-4',
    slug: 's3-data-lake',
    namespace: 'default',
    name: 'S3 Data Lake',
    description: 'Raw event storage feeding the analytics warehouse.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['s3', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'object-storage',
      system: ['00000000-0000-0000-0002-000000000004']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000005',
    workspace: WORKSPACE_ID,
    public_id: 'RES-5',
    slug: 'payments-postgres',
    namespace: 'default',
    name: 'Payments Postgres',
    description: 'Dedicated PostgreSQL cluster storing ledger and transaction state.',
    owner: TEAM_IDS.payments,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['postgres', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'database',
      technology_releases: [TECHNOLOGY_RELEASE_IDS.postgres15],
      system: ['00000000-0000-0000-0002-000000000003']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000006',
    workspace: WORKSPACE_ID,
    public_id: 'RES-6',
    slug: 'elasticsearch-cluster',
    namespace: 'default',
    name: 'Elasticsearch Cluster',
    description: 'Search index backing the Search Service.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.experimental,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['elasticsearch', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'search-index',
      technology_releases: [TECHNOLOGY_RELEASE_IDS.elasticsearch8],
      system: ['00000000-0000-0000-0002-000000000006']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000007',
    workspace: WORKSPACE_ID,
    public_id: 'RES-7',
    slug: 'analytics-warehouse',
    namespace: 'default',
    name: 'Analytics Warehouse',
    description: 'Columnar data warehouse powering internal reporting.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['warehouse', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'data-warehouse',
      system: ['00000000-0000-0000-0002-000000000004']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0005-000000000008',
    workspace: WORKSPACE_ID,
    public_id: 'RES-8',
    slug: 'cdn',
    namespace: 'default',
    name: 'CDN',
    description: 'Edge content delivery network fronting the customer portal.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['cdn', 'managed'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000005',
    data: {
      resource_type: 'cdn',
      system: ['00000000-0000-0000-0002-000000000001']
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Business glossary examples
  {
    id: GLOSSARY_IDS.categories.customer,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-1',
    slug: 'customer-and-identity',
    namespace: 'default',
    name: 'Customer & Identity',
    description: 'Terms describing customers, accounts, and identity concepts.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'customer'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.categories.data,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-2',
    slug: 'data-and-analytics',
    namespace: 'default',
    name: 'Data & Analytics',
    description: 'Terms describing data, metrics, and analytical products.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'data'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.categories.technology,
    workspace: WORKSPACE_ID,
    public_id: 'TCAT-3',
    slug: 'technology-and-architecture',
    namespace: 'default',
    name: 'Technology & Architecture',
    description: 'Terms describing systems, platforms, and architecture concepts.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'architecture'],
    links: [],
    schema_id: GLOSSARY_IDS.termCategorySchema,
    data: {},
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.terms.customerAccount,
    workspace: WORKSPACE_ID,
    public_id: 'TERM-1',
    slug: 'customer-account',
    namespace: 'default',
    name: 'Customer Account',
    description: 'A governed term for the account that represents a customer relationship.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'customer'],
    links: [],
    schema_id: GLOSSARY_IDS.termSchema,
    data: {
      definition: 'A record representing a customer relationship and its account-level context.',
      synonyms: ['Client Account', 'Customer Profile'],
      abbreviations: ['CA'],
      categories: [GLOSSARY_IDS.categories.customer],
      status: 'approved'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.terms.dataProduct,
    workspace: WORKSPACE_ID,
    public_id: 'TERM-2',
    slug: 'data-product',
    namespace: 'default',
    name: 'Data Product',
    description: 'A governed term for a discoverable and reusable data asset.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'data'],
    links: [],
    schema_id: GLOSSARY_IDS.termSchema,
    data: {
      definition: 'A data asset designed, documented, and operated for reuse by its consumers.',
      synonyms: ['Analytical Product'],
      abbreviations: ['DP'],
      categories: [GLOSSARY_IDS.categories.data],
      status: 'approved'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.terms.systemOfRecord,
    workspace: WORKSPACE_ID,
    public_id: 'TERM-3',
    slug: 'system-of-record',
    namespace: 'default',
    name: 'System of Record',
    description: 'A governed term for the authoritative source of a data domain.',
    owner: TEAM_IDS.platform,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'architecture'],
    links: [],
    schema_id: GLOSSARY_IDS.termSchema,
    data: {
      definition:
        'The authoritative system responsible for creating and maintaining a data record.',
      synonyms: ['Authoritative Source'],
      abbreviations: ['SoR'],
      categories: [GLOSSARY_IDS.categories.technology],
      status: 'proposed'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: GLOSSARY_IDS.terms.dataDomain,
    workspace: WORKSPACE_ID,
    public_id: 'TERM-4',
    slug: 'data-domain',
    namespace: 'default',
    name: 'Data Domain',
    description: 'A governed term for a cohesive area of business data ownership.',
    owner: TEAM_IDS.data,
    lifecycle: LIFECYCLE_IDS.production,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['glossary', 'data', 'architecture'],
    links: [],
    schema_id: GLOSSARY_IDS.termSchema,
    data: {
      definition: 'A bounded area of data with shared meaning, ownership, and governance rules.',
      synonyms: ['Information Domain'],
      abbreviations: ['DD'],
      categories: [GLOSSARY_IDS.categories.data, GLOSSARY_IDS.categories.technology],
      status: 'draft'
    },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  // Second workspace entities
  {
    id: '00000000-0000-0000-0011-000000000001',
    workspace: WORKSPACE2_ID,
    public_id: 'APP-1',
    slug: 'mobile-app',
    namespace: 'default',
    name: 'Mobile App',
    description: 'Cross-platform mobile application for iOS and Android.',
    owner: TEAM2_IDS.mobile,
    lifecycle: LIFECYCLE2_IDS.stable,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['mobile', 'customer-facing'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000011',
    data: { platform: 'ios' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000001',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-1',
    slug: 'notifications-service',
    namespace: 'default',
    name: 'Notifications Service',
    description: 'Handles push notifications and email delivery.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.beta,
    target_lifecycle: LIFECYCLE2_IDS.stable,
    target_lifecycle_date: '2026-09-01',
    tags: ['nodejs', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Node' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000002',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-2',
    slug: 'delivery-service',
    namespace: 'default',
    name: 'Delivery Service',
    description: 'Coordinates outbound delivery jobs for notifications.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.active,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['worker', 'messaging'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Rust' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0011-000000000002',
    workspace: WORKSPACE2_ID,
    public_id: 'APP-2',
    slug: 'admin-app',
    namespace: 'default',
    name: 'Admin App',
    description: 'Internal web application for support and operations staff.',
    owner: TEAM2_IDS.mobile,
    lifecycle: LIFECYCLE2_IDS.beta,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['internal', 'web'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000011',
    data: { platform: 'web' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0011-000000000003',
    workspace: WORKSPACE2_ID,
    public_id: 'APP-3',
    slug: 'partner-portal',
    namespace: 'default',
    name: 'Partner Portal',
    description: 'Web application used by external delivery partners.',
    owner: TEAM2_IDS.mobile,
    lifecycle: LIFECYCLE2_IDS.active,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['partner-facing', 'web'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000011',
    data: { platform: 'web' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000003',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-3',
    slug: 'auth-service',
    namespace: 'default',
    name: 'Auth Service',
    description: 'Issues and validates session tokens for mobile and web clients.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.stable,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['go', 'security'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Go' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000004',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-4',
    slug: 'payments-service',
    namespace: 'default',
    name: 'Payments Service',
    description: 'Handles in-app purchases and subscription billing.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.stable,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['java', 'revenue'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Java' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000005',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-5',
    slug: 'search-service',
    namespace: 'default',
    name: 'Search Service',
    description: 'Provides in-app search across catalog and content.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.beta,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['rust', 'search'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Rust' },
    project_id: null,
    created_at: now,
    updated_at: now
  },
  {
    id: '00000000-0000-0000-0012-000000000006',
    workspace: WORKSPACE2_ID,
    public_id: 'SVC-6',
    slug: 'analytics-service',
    namespace: 'default',
    name: 'Analytics Service',
    description: 'Collects client usage events for product analytics.',
    owner: TEAM2_IDS.backend,
    lifecycle: LIFECYCLE2_IDS.active,
    target_lifecycle: null,
    target_lifecycle_date: null,
    tags: ['python', 'internal'],
    links: [],
    schema_id: '00000000-0000-0000-0000-000000000012',
    data: { technology: 'Python' },
    project_id: null,
    created_at: now,
    updated_at: now
  }
];

const seedSchemaById = new Map(seedSchemas.map(schema => [schema.id, schema]));

const stripSeedApiRelationshipFields = (data: SeedEntityInput['data']): SeedEntityInput['data'] => {
  const { provides_apis: _providesApis, consumes_apis: _consumesApis, ...remaining } = data;
  return remaining;
};

export const seedEntities: Entity[] = seedEntitiesRaw.map(entity => {
  const schema = seedSchemaById.get(entity.schema_id);
  if (!schema)
    throw new Error(`Seed entity '${entity.id}' references unknown schema '${entity.schema_id}'`);
  // Seed fixtures are inserted directly (bootstrapSeed.ts), bypassing the normal create path that
  // materializes `type: 'derived'` fields on write - do it here so seeded entities carry computed
  // derived values (e.g. Risk's residual_risk_score) just like entities created through the app.
  // Typed relations are inserted after entities during bootstrap, so expose their initial
  // context as empty arrays. bootstrapSeed recalculates all derived fields after relation rows
  // have been inserted and replaces these provisional values with the relation-aware results.
  const entityData = stripSeedApiRelationshipFields(entity.data);
  const initialDerivedContext = {
    ...entityData,
    ...Object.fromEntries(
      schema.fields.filter(field => field.type === 'typedRelation').map(field => [field.id, []])
    )
  };
  const data = materializeDerivedFields(
    schema.fields,
    entityData,
    { objectType: 'entity', objectId: entity.id },
    schema.groups,
    initialDerivedContext
  );
  return { ...entity, data, completeness: computeEntityCompleteness({ ...entity, data }, schema) };
});
