name: Benchmarks

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.3.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pnpm vitest bench
          token: ${{ secrets.CODSPEED_TOKEN }}
